/* Generated by Studio from .studio/ — do not edit.
 * Rewritten every time the project is opened. Anything you change here is
 * lost; the files that are yours to edit are App.jsx, CanvasPanel.* and
 * shell.css, which Studio writes once and never touches again. */
import { DesignSystemProvider } from '@alm-design/design-system'
import '@alm-design/design-system/dist/index.css'

export function Providers({ children }) {
  return <DesignSystemProvider platform="ios" dir="ltr">{children}</DesignSystemProvider>
}

/** No i18n in this project — one locale, left to right. */
export function useShellLanguage() {
  return { lang: 'en', dir: 'ltr', setLang: () => {}, locales: ["en"] }
}
