/* Generated by Studio from .studio/ — do not edit.
 * Rewritten every time the project is opened. Anything you change here is
 * lost; the files that are yours to edit are App.jsx, CanvasPanel.* and
 * shell.css, which Studio writes once and never touches again. */
export function Providers({ children }) {
  return children
}

/** No i18n in this project — one locale, left to right. */
export function useShellLanguage() {
  return { lang: 'en', dir: 'ltr', setLang: () => {}, locales: ["en"] }
}
