/* Generated by Studio from .studio/ — do not edit.
 * Rewritten every time the project is opened. Anything you change here is
 * lost; the files that are yours to edit are App.jsx, CanvasPanel.* and
 * shell.css, which Studio writes once and never touches again. */
import CanonicalScreen from '../src/screens/CanonicalScreen'
import EsimActivation from '../src/screens/ESimActivation'
import EsimActivationAr from '../src/screens/ESimActivationAr'
import NonCanonicalScreen from '../src/screens/NonCanonicalScreen'
import Page from '../src/screens/Page'
import Page2 from '../src/screens/Page2'

/** Every screen in `pages/`, by the same id Studio addresses it with. */
export const SCREENS = [
  { key: "canonical-screen", label: "CanonicalScreen", Component: CanonicalScreen },
  { key: "esim-activation", label: "ESimActivation", Component: EsimActivation },
  { key: "esim-activation-ar", label: "ESimActivationAr", Component: EsimActivationAr },
  { key: "non-canonical-screen", label: "NonCanonicalScreen", Component: NonCanonicalScreen },
  { key: "page", label: "Page", Component: Page },
  { key: "page2", label: "Page2", Component: Page2 },
]

/** Studio's boards, in file order. One board is one tab; frames keep the x/y the author arranged. */
export const BOARDS = [
  {
    id: "7e27e18c-87f5-42fb-bb59-c03e772c09e8",
    name: "Board 1",
    frames: [
      {"key":"d5dbce2b-7bb5-48c8-8485-29c5b5bbf355","pageId":"esim-activation","label":"ESimActivation","x":1104,"y":880,"width":393,"height":1057},
      {"key":"b6a8f10c-31d4-4e0a-9c22-4d0f9a2c7311","pageId":"esim-activation-ar","label":"ESimActivationAr","x":1560,"y":880,"width":393,"height":1057},
      {"key":"ebb9123f-fba3-4b65-92a8-048b59be016b","pageId":"canonical-screen","label":"CanonicalScreen","x":-417,"y":1182,"width":393,"height":852},
      {"key":"9d32a90e-bf6a-4b90-bd17-f16b3940594f","pageId":"page","label":"Page","x":0,"y":1760,"width":393,"height":852},
      {"key":"014b6a1e-e986-466b-ac83-cc563da6de6b","pageId":"non-canonical-screen","label":"NonCanonicalScreen","x":1104,"y":1760,"width":393,"height":852},
      {"key":"23639168-64cf-41d3-89cd-8170f957159c","pageId":"page2","label":"Page2","x":0,"y":2640,"width":393,"height":852},
    ],
    notes: [

    ],
    docs: [

    ],
  },
]

/** The board-level defaults a frame inherits when it carries no size of its own. */
/** The project's name, drawn top-left. The last word takes the accent. */
export const PROJECT_NAME = "__canonical-fixture"

export const FRAME_DEFAULTS = {"width":393,"height":852}

/** What the board was last previewing in Studio — the shell opens on the same thing. */
export const PREVIEW_AXES = {"direction":"ltr","colorScheme":"dark","locale":"en"}

/** Locale codes this project's dictionary declares. */
export const LOCALES = ["en"]

/**
 * The interactions authored on the board: which element, on which screen,
 * goes where. A link addresses its element by `indexPath` — the child-index
 * path from the page root — because the exported app has none of Studio's
 * node-id attributes to match on, and an index path resolves against plain
 * rendered DOM. See `Player.jsx`.
 */
export const LINKS = []

export function applyColorSchemeGate() {
  // This project declares no dark-mode gate of its own, so the
  // `data-theme` and `color-scheme` App.jsx already sets are the whole
  // mechanism. Detected mechanism: none.
}
