/* Generated by Studio from .studio/ — do not edit.
 * Rewritten every time the project is opened. Anything you change here is
 * lost; the files that are yours to edit are App.jsx, CanvasPanel.* and
 * shell.css, which Studio writes once and never touches again. */
import CanonicalScreen from '../src/screens/CanonicalScreen'
import NonCanonicalScreen from '../src/screens/NonCanonicalScreen'

/** Every screen in `pages/`, by the same id Studio addresses it with. */
export const SCREENS = [
  { key: "canonical-screen", label: "CanonicalScreen", Component: CanonicalScreen },
  { key: "non-canonical-screen", label: "NonCanonicalScreen", Component: NonCanonicalScreen },
]

/** Studio's boards, in file order. One board is one tab; frames keep the x/y the author arranged. */
export const BOARDS = [

]

/** The board-level defaults a frame inherits when it carries no size of its own. */
/** The project's name, drawn top-left. The last word takes the accent. */
export const PROJECT_NAME = "__canonical-fixture"

export const FRAME_DEFAULTS = {"width":393,"height":852}

/** What the board was last previewing in Studio — the shell opens on the same thing. */
export const PREVIEW_AXES = {"direction":"ltr","colorScheme":"dark","locale":"en"}

/** Locale codes this project's dictionary declares. */
export const LOCALES = ["en"]

/**
 * The interactions authored on the board: which element, on which screen,
 * goes where. A link addresses its element by `indexPath` — the child-index
 * path from the page root — because the exported app has none of Studio's
 * node-id attributes to match on, and an index path resolves against plain
 * rendered DOM. See `Player.jsx`.
 */
export const LINKS = []

export function applyColorSchemeGate() {
  // This project declares no dark-mode gate of its own, so the
  // `data-theme` and `color-scheme` App.jsx already sets are the whole
  // mechanism. Detected mechanism: none.
}
