import { createContext, useContext, useMemo, useState, type ReactNode } from 'react'
import { translations, defaultLocale, type Locale } from './translations'

/**
 * LanguageContext — the current language, the strings for it, and the way to
 * switch. Generated by Studio.
 *
 * The default value carries the English dictionary on purpose: `useLanguage()`
 * works with no <LanguageProvider> mounted, so adding a translated string to a
 * component can never break a screen. Wrap your app in <LanguageProvider> when
 * you want language switching and RTL to actually take effect.
 */
const LanguageContext = createContext({
  lang: defaultLocale,
  dir: 'ltr' as 'ltr' | 'rtl',
  t: translations[defaultLocale],
  setLang: (_lang: Locale) => {},
})

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Locale>(defaultLocale)

  const value = useMemo(
    () => ({
      lang,
      dir: lang === 'ar' ? ('rtl' as const) : ('ltr' as const),
      t: translations[lang],
      setLang,
    }),
    [lang],
  )

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

/** `const { t } = useLanguage()` — the strings for the active language. */
export function useLanguage() {
  const ctx = useContext(LanguageContext)
  return ctx
}
