import type { ThemeName, TokenModel } from './types.js';

/**
 * `emitCss(model, theme)` — the FROZEN engine API's CSS emitter
 * (ADR-0022: "emitCss(theme)"). PURE — string in (via `TokenModel`),
 * string out; no fs. Mirrors the hand-written `design-system/src/tokens/
 * colors.css` dark-mode pattern so the emitted stylesheet composes the
 * same way: `light` is a plain `:root {}` block (the default); `dark` is
 * BOTH a `prefers-color-scheme` media query (respecting an explicit
 * `data-theme="light"` override) AND a `:root[data-theme="dark"]` forced
 * block, so a consumer can either follow the OS theme or pin one.
 *
 * Every token is emitted for the requested theme regardless of whether its
 * value actually differs between themes (theme-independent groups like
 * spacing/rounded/elevation/typography simply repeat the same value under
 * both) — simplicity over minimal-diff output; harmless, valid CSS either
 * way.
 *
 * Dir-agnostic by construction (playbook §9 / P4 RTL requirement): this
 * emitter never reads or branches on any `dir`/`[dir=...]` concept — CSS
 * custom-property VALUES (colors, spacing, radii, shadows, font metrics)
 * are direction-independent; only LAYOUT (a file-app's own CSS) is
 * direction-dependent, and that is out of this emitter's scope entirely.
 */
export function emitCss(model: TokenModel, theme: ThemeName): string {
  const header = `/* AUTO-GENERATED by @ccs/tokens (${theme} theme) — do not hand-edit.\n   Source: design-system/src/tokens/tokens.js — regenerated by the\n   sync-daemon's design-system watch (playbook §4/P4). */\n`;

  const declarations = model.tokens.map(
    (t) => `  ${formatCssVarName(t.cssVar)}: ${formatCssValue(t.value[theme])};`,
  );

  if (theme === 'light') {
    return `${header}:root {\n${declarations.join('\n')}\n}\n`;
  }

  return (
    header +
    [
      '@media (prefers-color-scheme: dark) {',
      '  :root:not([data-theme="light"]) {',
      declarations.map((d) => `  ${d}`).join('\n'),
      '  }',
      '}',
      '',
      ':root[data-theme="dark"] {',
      declarations.join('\n'),
      '}',
      '',
    ].join('\n')
  );
}

/**
 * AUDIT-7 blocker close-out — sink-side defense-in-depth, independent of
 * `packages/sync-daemon/src/token-crud.ts`'s authoritative wire-boundary
 * validation. `emitCss` is a PURE, standalone part of the FROZEN
 * `@ccs/tokens` engine API (ADR-0022): it must not assume every
 * `TokenModel` handed to it was built from a validated token-CRUD request
 * (a hand-built `TokenModel`, an older on-disk token predating the
 * boundary fix, or a future non-daemon caller could all carry an unsafe
 * name/value). A malformed name/value here must FAIL the emit rather than
 * silently produce CSS that breaks out of its declaration or rule — same
 * fail-closed posture as `token-rebuild.ts`'s `rebuildTokenOutputs`, which
 * already catches a thrown error from this pure function and turns it into
 * `{ok:false, reason}` (no output is written, no `tokens-changed` is
 * broadcast).
 */
const SAFE_CSS_VAR_NAME_PATTERN = /^--[A-Za-z0-9_-]+$/;
const CSS_BREAKING_VALUE_PATTERN = /[;{}]|\/\*|\*\/|[\r\n]/;

function formatCssVarName(name: string): string {
  if (!SAFE_CSS_VAR_NAME_PATTERN.test(name)) {
    throw new Error(`refusing to emit CSS: unsafe custom-property name "${name}"`);
  }
  return name;
}

function formatCssValue(value: string | number): string {
  if (typeof value === 'number') return String(value);
  if (CSS_BREAKING_VALUE_PATTERN.test(value)) {
    throw new Error(
      `refusing to emit CSS: token value "${value}" contains a sequence that could break out of ` +
        'its declaration (";", "{", "}", "/*", "*/", or a newline)',
    );
  }
  return value;
}
