import { kebabCase } from './kebab.js';
import { tokensByGroup, type TokenModel } from './types.js';

/**
 * `emitTailwindPreset(model)` — the FROZEN engine API's Tailwind emitter
 * (ADR-0022). PURE. Returns a plain-object Tailwind v3-style "preset"
 * (`{theme:{extend:{...}}}`) whose every utility value is a `var(--css-
 * var)` reference into the CSS emitted by `emitCss` — so at RUNTIME the
 * browser resolves whichever theme's custom-property scope is active
 * (`:root` / `[data-theme]`) and the generated Tailwind class (`bg-aqua-
 * 100`, `rounded-lg`, `shadow-floating`, ...) tracks it live, with no
 * rebuild needed for a theme *switch* (only a token *value* change needs
 * `emitCss`/this to re-run).
 *
 * Consumed by `templates/file-app/tailwind.config.js` via Tailwind v4's
 * JS-config-compat `presets: [preset]` (the template already loads a JS
 * config through `@config` from `src/index.css` — v4 still merges
 * `theme.extend` from a JS preset the same way v3 did).
 */
export interface TailwindPreset {
  theme: {
    extend: {
      colors: Record<string, string>;
      spacing: Record<string, string>;
      borderRadius: Record<string, string>;
      boxShadow: Record<string, string>;
      fontFamily: Record<string, string[]>;
      fontWeight: Record<string, string>;
      fontSize: Record<string, [string, { lineHeight?: string; letterSpacing?: string }]>;
    };
  };
}

export function emitTailwindPreset(model: TokenModel): TailwindPreset {
  const colors: Record<string, string> = {};
  for (const t of tokensByGroup(model, 'color')) colors[kebabCase(t.name)] = `var(${t.cssVar})`;

  const spacing: Record<string, string> = {};
  for (const t of tokensByGroup(model, 'spacing')) {
    spacing[t.name === 'base' ? 'DEFAULT' : kebabCase(t.name)] = `var(${t.cssVar})`;
  }

  const borderRadius: Record<string, string> = {};
  for (const t of tokensByGroup(model, 'rounded')) {
    borderRadius[t.name === 'base' ? 'DEFAULT' : kebabCase(t.name)] = `var(${t.cssVar})`;
  }

  const boxShadow: Record<string, string> = {};
  for (const t of tokensByGroup(model, 'elevation')) boxShadow[kebabCase(t.name)] = `var(${t.cssVar})`;

  interface ScaleAccum {
    family?: string;
    size?: string;
    weight?: string;
    lh?: string;
    ls?: string;
  }
  const scales = new Map<string, ScaleAccum>();
  for (const t of tokensByGroup(model, 'typography')) {
    const [scale, field] = t.name.split('.');
    if (!scale || !field) continue;
    const entry: ScaleAccum = scales.get(scale) ?? {};
    const ref = `var(${t.cssVar})`;
    if (field === 'fontFamily') entry.family = ref;
    else if (field === 'fontSize') entry.size = ref;
    else if (field === 'fontWeight') entry.weight = ref;
    else if (field === 'lineHeight') entry.lh = ref;
    else if (field === 'letterSpacing') entry.ls = ref;
    scales.set(scale, entry);
  }

  const fontFamily: Record<string, string[]> = {};
  const fontWeight: Record<string, string> = {};
  const fontSize: Record<string, [string, { lineHeight?: string; letterSpacing?: string }]> = {};
  for (const [scale, entry] of scales) {
    const key = kebabCase(scale);
    if (entry.family) fontFamily[key] = [entry.family];
    if (entry.weight) fontWeight[key] = entry.weight;
    if (entry.size) {
      const opts: { lineHeight?: string; letterSpacing?: string } = {};
      if (entry.lh) opts.lineHeight = entry.lh;
      if (entry.ls) opts.letterSpacing = entry.ls;
      fontSize[key] = [entry.size, opts];
    }
  }

  return { theme: { extend: { colors, spacing, borderRadius, boxShadow, fontFamily, fontWeight, fontSize } } };
}

/** Serializes a preset to a standalone ESM module the file-app's
 * `tailwind.config.js` imports via a RELATIVE path (no `@ccs/*` runtime
 * dep — playbook §4/P0 "standalone" contract, AUDIT-1). Pure string
 * building (`JSON.stringify` on a plain data object is valid JS object-
 * literal syntax) — the actual fs write happens at the daemon boundary. */
export function serializePresetModule(preset: TailwindPreset): string {
  return (
    '// AUTO-GENERATED by @ccs/tokens — do not hand-edit.\n' +
    '// Source: design-system/src/tokens/tokens.js — regenerated by the\n' +
    "// sync-daemon's design-system watch (playbook §4/P4).\n" +
    `export default ${JSON.stringify(preset, null, 2)};\n`
  );
}
