/* Generated by Studio from .studio/ — do not edit.
 * Rewritten every time the project is opened. Anything you change here is
 * lost; the files that are yours to edit are App.jsx, CanvasPanel.* and
 * shell.css, which Studio writes once and never touches again. */
import { LanguageProvider, useLanguage } from '../i18n/LanguageContext'
import { DesignSystemProvider } from '@alm-design/design-system'
import '@alm-design/design-system/dist/index.css'

/**
 * The project's own language provider, with the design system's direction
 * fed from it. The DS resolves direction in JavaScript, so `dir` on <html>
 * alone leaves every mirrored chevron pointing the wrong way.
 */
export function Providers({ children }) {
  return (
    <LanguageProvider>
      <DirectionBridge>{children}</DirectionBridge>
    </LanguageProvider>
  )
}

function DirectionBridge({ children }) {
  const { dir } = useLanguage()
  return (
    <DesignSystemProvider platform="ios" dir={dir}>{children}</DesignSystemProvider>
  )
}

/** The shape App.jsx expects, whether or not this project has i18n. */
export function useShellLanguage() {
  const { lang, dir, setLang } = useLanguage()
  return { lang, dir, setLang, locales: ["en","ar"] }
}
