/* Generated by Studio from .studio/ — do not edit.
 * Rewritten every time the project is opened. Anything you change here is
 * lost; the files that are yours to edit are App.jsx, CanvasPanel.* and
 * shell.css, which Studio writes once and never touches again. */
import Onboarding from '../pages/Onboarding'
import Sms from '../pages/SMS'
import SignUp from '../pages/SignUp'

/** Every screen in `pages/`, by the same id Studio addresses it with. */
export const SCREENS = [
  { key: "onboarding", label: "Onboarding", Component: Onboarding },
  { key: "sms", label: "SMS", Component: Sms },
  { key: "sign-up", label: "SignUp", Component: SignUp },
]

/** Studio's boards, in file order. One board is one tab; frames keep the x/y the author arranged. */
export const BOARDS = [
  {
    id: "2fd078d6-209f-44df-842e-4bda43d97ed5",
    name: "Board 1",
    frames: [
      {"key":"3884d231-f0eb-4dcb-a48b-49e01249f3ad","pageId":"onboarding","label":"Onboarding","x":422,"y":901,"width":393,"height":808},
      {"key":"d7132d36-dbde-434c-b257-1ff2d0ce909f","pageId":"sms","label":"SMS","x":-2,"y":901,"width":393,"height":804},
      {"key":"2a978b29-58cf-40b2-bf8c-efb5873db9d3","pageId":"sign-up","label":"SignUp","x":-422,"y":901,"width":393,"height":788},
    ],
    notes: [
      {"id":"bb7731f0-d5b9-467f-8b72-e2d588782623","x":-877.4360057479422,"y":811.5117580123127,"w":216.9538838520047,"h":126.12189749690015,"text":"Testing the sticky notes","color":"yellow"},
    ],
    docs: [
      {"id":"2f9af55e-0d53-415c-b494-5a42cec1a594","x":-877.4360057479422,"y":980.390375135975,"w":415.5648781155613,"h":320.47660615163517,"html":"<h1>Best test for a doc</h1>this doc is amazing AF<div><br></div><div><h3>hooooray what. a doc</h3><div><ul><li>who made this amazing work</li><li>it's me hehe</li><li>kbasl;dfsdfna;dsf</li></ul></div></div>"},
    ],
  },
]

/** The board-level defaults a frame inherits when it carries no size of its own. */
/** The project's name, drawn top-left. The last word takes the accent. */
export const PROJECT_NAME = "test4"

export const FRAME_DEFAULTS = {"width":393,"height":852}

/** What the board was last previewing in Studio — the shell opens on the same thing. */
export const PREVIEW_AXES = {"direction":"ltr","colorScheme":"dark","locale":"en"}

/** Locale codes this project's dictionary declares. */
export const LOCALES = ["en","ar"]

/**
 * The interactions authored on the board: which element, on which screen,
 * goes where. A link addresses its element by `indexPath` — the child-index
 * path from the page root — because the exported app has none of Studio's
 * node-id attributes to match on, and an index path resolves against plain
 * rendered DOM. See `Player.jsx`.
 */
export const LINKS = [
  {
    "id": "bdb3afb0-d601-4ffc-b1f0-e55daa7a8b49",
    "origin": "design",
    "source": {
      "pageId": "sign-up",
      "node": {
        "nodeId": "pages/SignUp.tsx:30:16",
        "indexPath": [
          0,
          1,
          1,
          0,
          1,
          0
        ],
        "moduleId": "alm.Button",
        "textSnippet": ""
      }
    },
    "trigger": "click",
    "action": "overlay",
    "targetPageId": "sms",
    "transition": "sheet"
  },
  {
    "id": "72c775ca-bd15-481e-b607-6b2e33fd75b4",
    "origin": "design",
    "source": {
      "pageId": "onboarding",
      "node": {
        "nodeId": "pages/Onboarding.tsx:45:10",
        "indexPath": [
          0,
          1,
          1
        ],
        "moduleId": "base.container",
        "textSnippet": ""
      }
    },
    "trigger": "click",
    "action": "navigate",
    "targetPageId": "sign-up",
    "transition": "slide-left"
  },
  {
    "id": "738d5631-3626-4542-963b-1216d6e5ab31",
    "origin": "design",
    "source": {
      "pageId": "sms",
      "node": {
        "nodeId": "pages/SMS.tsx:11:10",
        "indexPath": [
          0,
          0,
          0
        ],
        "moduleId": "studio.instance",
        "textSnippet": ""
      }
    },
    "trigger": "click",
    "action": "back",
    "targetPageId": null
  },
  {
    "id": "b14ba0be-ab2c-4ca4-958d-753cd53d678b",
    "origin": "design",
    "source": {
      "pageId": "sign-up",
      "node": {
        "nodeId": "pages/SignUp.tsx:21:8~components/SheetHeader.tsx:23:12",
        "indexPath": [
          0,
          0,
          0,
          1,
          0,
          0
        ],
        "moduleId": "alm.GlassButton",
        "textSnippet": ""
      }
    },
    "trigger": "click",
    "action": "back",
    "targetPageId": null
  },
  {
    "id": "ea91ae57-7b4a-46fb-b51f-e05c9bb9ee29",
    "origin": "design",
    "source": {
      "pageId": "sms",
      "node": {
        "nodeId": "pages/SMS.tsx:11:10~components/SheetHeader.tsx:22:10",
        "indexPath": [
          0,
          0,
          0,
          0,
          1,
          0
        ],
        "moduleId": "base.container",
        "textSnippet": ""
      }
    },
    "trigger": "click",
    "action": "back",
    "targetPageId": null
  },
  {
    "id": "9ef314f0-8cc3-4167-abb1-37a02d9f4094",
    "origin": "design",
    "source": {
      "pageId": "sms",
      "node": {
        "nodeId": "pages/SMS.tsx:36:14",
        "indexPath": [
          0,
          1,
          1,
          1,
          5
        ],
        "moduleId": "base.container",
        "textSnippet": ""
      }
    },
    "trigger": "click",
    "action": "navigate",
    "targetPageId": "onboarding",
    "transition": "slide-left"
  }
]

export function applyColorSchemeGate(html, scheme) {
  // The project's own gate: [data-theme='dark']
  html.setAttribute("data-theme", scheme === 'dark' ? "dark" : 'light')
}
