/**
 * registryFile — the generated half of the preview shell: everything the shell
 * knows that comes out of `.studio/`.
 *
 * Two files, both rewritten on every project open, both named `.generated` and
 * both carrying a do-not-edit banner:
 *
 *   - `registry.generated.jsx` — the screens, the boards, the frame geometry,
 *     the preview axes, and the project's own dark-mode gate.
 *   - `providers.generated.jsx` — the provider stack, which varies by project:
 *     a project with `i18n/` gets its `LanguageProvider`, a project with the
 *     design system installed gets `DesignSystemProvider`, and a project with
 *     neither gets a passthrough.
 *
 * ## Why generated files at all, rather than reading JSON at runtime
 *
 * The shell could `fetch('.studio/boards.json')` — and then the downloaded zip
 * would be broken, because the download excludes `.studio/` by design. Baking
 * the design layer into source is what makes "Download the code" produce
 * something that RUNS. It is also what makes the board legible in a git diff.
 *
 * ## Why the providers are generated and `App.jsx` is not
 *
 * A static import cannot be conditional, so the one thing that genuinely
 * differs between projects — which providers exist — has to be decided at
 * generation time. Putting that seam in its own tiny generated file is what
 * lets `App.jsx` be written once and then belong to the user.
 */
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { parseBoardsFile, type Board, type BoardsFile } from '@core/studio-board'
import { boardsFilePath } from '../boardFrames'
import { PROTOTYPE_SHELL_DIR, type ShellFile } from './shellPaths'

const BANNER = `/* Generated by Studio from .studio/ — do not edit.
 * Rewritten every time the project is opened. Anything you change here is
 * lost; the files that are yours to edit are App.jsx, CanvasPanel.* and
 * shell.css, which Studio writes once and never touches again. */
`

/** One screen the shell can render: its page id, its title, and the file it lives in. */
export interface ShellScreen {
  pageId: string
  title: string
  /** POSIX path relative to the workspace root, e.g. `pages/SignUp.tsx`. */
  relFile: string
}

export interface ShellRegistryInput {
  /** The project's own name, drawn as the shell's wordmark. */
  projectName: string
  screens: readonly ShellScreen[]
  boards: BoardsFile
  frameDefaults: { width: number; height: number }
  previewAxes: { direction: string; colorScheme: string; locale?: string }
  /** The project's own dark-mode gate, as `projectProbe` detected it. `null` when it has none. */
  colorScheme: { mechanism: string; selector?: string } | null
  /** True when `i18n/LanguageContext` exists and exports `LanguageProvider`. */
  hasLanguageProvider: boolean
  /** Locale codes the project's dictionary declares, for the EN/AR control. */
  locales: readonly string[]
  /** True when `@alm-design/design-system` is a dependency. */
  hasDesignSystem: boolean
  /** The prototype links authored in Studio, from `.studio/prototype.json`. */
  links: readonly unknown[]
}

/** A safe, unique JS identifier for a page component import. */
function identifierFor(pageId: string, taken: Set<string>): string {
  const base = pageId
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
  const safe = /^[A-Za-z]/.test(base) ? base : `Screen${base}`
  let name = safe || 'Screen'
  let n = 2
  while (taken.has(name)) name = `${safe}${n++}`
  taken.add(name)
  return name
}

/** `pages/SignUp.tsx` -> `../pages/SignUp` — extensionless, which is what Vite resolves. */
function importPathFor(relFile: string): string {
  return `../${relFile.replace(/\.(tsx|jsx|ts|js)$/, '')}`
}

/**
 * The runtime form of the project's dark-mode gate.
 *
 * `applyColorSchemeGate` mirrors `applyPreviewAxesToFrameDocument`'s class /
 * attribute branch, minus the canvas-only attributes: `data-studio-scheme`
 * exists so Studio can rewrite `prefers-color-scheme` blocks into something a
 * board can toggle, and there is no board here — a real browser answers
 * `prefers-color-scheme` for itself.
 */
function colorSchemeGateSource(colorScheme: ShellRegistryInput['colorScheme']): string {
  const selector = colorScheme?.mechanism === 'class' ? colorScheme.selector : undefined
  const attribute = selector ? /^\[([a-zA-Z-]+)(?:=['"]?([^\]'"]+)['"]?)?\]$/.exec(selector) : null
  const className = selector ? /^\.([\w-]+)$/.exec(selector) : null

  if (attribute) {
    const name = attribute[1]!
    const onValue = attribute[2] ?? 'dark'
    return (
      `export function applyColorSchemeGate(html, scheme) {\n` +
      `  // The project's own gate: ${selector}\n` +
      `  html.setAttribute(${JSON.stringify(name)}, scheme === 'dark' ? ${JSON.stringify(onValue)} : 'light')\n` +
      `}\n`
    )
  }
  if (className) {
    return (
      `export function applyColorSchemeGate(html, scheme) {\n` +
      `  // The project's own gate: ${selector}. A class gate has no light\n` +
      `  // counterpart to add — the class being off IS light.\n` +
      `  html.classList.toggle(${JSON.stringify(className[1]!)}, scheme === 'dark')\n` +
      `}\n`
    )
  }
  return (
    `export function applyColorSchemeGate() {\n` +
    `  // This project declares no dark-mode gate of its own, so the\n` +
    `  // \`data-theme\` and \`color-scheme\` App.jsx already sets are the whole\n` +
    `  // mechanism. Detected mechanism: ${colorScheme?.mechanism ?? 'none'}.\n` +
    `}\n`
  )
}

/** One board's frames, in a stable order, carrying whatever geometry the author gave them. */
function boardSource(board: Board, frameDefaults: { width: number; height: number }, titleByPageId: Map<string, string>): string {
  const frames = board.frames
    .filter((frame) => titleByPageId.has(frame.pageId))
    .map((frame) => {
      const entry: Record<string, unknown> = {
        key: frame.id,
        pageId: frame.pageId,
        label: titleByPageId.get(frame.pageId) ?? frame.pageId,
        x: Math.round(frame.x),
        y: Math.round(frame.y),
        width: Math.round(frame.width ?? frameDefaults.width),
        height: Math.round(frame.height ?? frameDefaults.height),
      }
      if (frame.axes && (frame.axes.direction || frame.axes.colorScheme)) entry.axes = frame.axes
      return `      ${JSON.stringify(entry)},`
    })
    .join('\n')

  const notes = (board.notes ?? [])
    .map((note) => `      ${JSON.stringify(note)},`)
    .join('\n')
  const docs = (board.docs ?? [])
    .map((doc) => `      ${JSON.stringify(doc)},`)
    .join('\n')

  return (
    `  {\n` +
    `    id: ${JSON.stringify(board.id)},\n` +
    `    name: ${JSON.stringify(board.name)},\n` +
    `    frames: [\n${frames}\n    ],\n` +
    `    notes: [\n${notes}\n    ],\n` +
    `    docs: [\n${docs}\n    ],\n` +
    `  },`
  )
}

/**
 * `prototype/registry.generated.jsx`.
 *
 * A board with no frames still gets an entry: it is a tab the author created,
 * and hiding it would make the shell disagree with Studio about how many
 * boards exist. A FRAME whose page no longer exists is dropped — that one
 * would be a broken import, not an empty tab.
 */
export function renderRegistryFile(input: ShellRegistryInput): string {
  const taken = new Set<string>()
  const named = input.screens.map((screen) => ({ ...screen, ident: identifierFor(screen.pageId, taken) }))
  const titleByPageId = new Map(named.map((screen) => [screen.pageId, screen.title]))

  const imports = named.map((s) => `import ${s.ident} from '${importPathFor(s.relFile)}'`).join('\n')
  const screens = named
    .map((s) => `  { key: ${JSON.stringify(s.pageId)}, label: ${JSON.stringify(s.title)}, Component: ${s.ident} },`)
    .join('\n')
  const boards = input.boards.boards.map((board) => boardSource(board, input.frameDefaults, titleByPageId)).join('\n')

  return (
    `${BANNER}${imports}${imports ? '\n' : ''}\n` +
    `/** Every screen in \`pages/\`, by the same id Studio addresses it with. */\n` +
    `export const SCREENS = [\n${screens}\n]\n\n` +
    `/** Studio's boards, in file order. One board is one tab; frames keep the x/y the author arranged. */\n` +
    `export const BOARDS = [\n${boards}\n]\n\n` +
    `/** The board-level defaults a frame inherits when it carries no size of its own. */\n` +
    `/** The project's name, drawn top-left. The last word takes the accent. */\n` +
    `export const PROJECT_NAME = ${JSON.stringify(input.projectName)}\n\n` +
    `export const FRAME_DEFAULTS = ${JSON.stringify(input.frameDefaults)}\n\n` +
    `/** What the board was last previewing in Studio — the shell opens on the same thing. */\n` +
    `export const PREVIEW_AXES = ${JSON.stringify(input.previewAxes)}\n\n` +
    `/** Locale codes this project's dictionary declares. */\n` +
    `export const LOCALES = ${JSON.stringify(input.locales)}\n\n` +
    `/**\n` +
    ` * The interactions authored on the board: which element, on which screen,\n` +
    ` * goes where. A link addresses its element by \`indexPath\` — the child-index\n` +
    ` * path from the page root — because the exported app has none of Studio's\n` +
    ` * node-id attributes to match on, and an index path resolves against plain\n` +
    ` * rendered DOM. See \`Player.jsx\`.\n` +
    ` */\n` +
    `export const LINKS = ${JSON.stringify(input.links, null, 2)}\n\n` +
    colorSchemeGateSource(input.colorScheme)
  )
}

/**
 * `prototype/providers.generated.jsx`.
 *
 * `useShellLanguage` always returns the same shape — `{ lang, dir, setLang,
 * locales }` — so `App.jsx` never branches on whether this project has i18n.
 * A project without it gets a single-locale, LTR answer and the language
 * control simply does not render.
 */
export function renderProvidersFile(input: ShellRegistryInput): string {
  const locales = JSON.stringify(input.locales.length > 0 ? input.locales : ['en'])

  if (!input.hasLanguageProvider) {
    const body = input.hasDesignSystem
      ? `import { DesignSystemProvider } from '@alm-design/design-system'\nimport '@alm-design/design-system/dist/index.css'\n\n` +
        `export function Providers({ children }) {\n` +
        `  return <DesignSystemProvider platform="ios" dir="ltr">{children}</DesignSystemProvider>\n` +
        `}\n`
      : `export function Providers({ children }) {\n  return children\n}\n`
    return (
      `${BANNER}${body}\n` +
      `/** No i18n in this project — one locale, left to right. */\n` +
      `export function useShellLanguage() {\n` +
      `  return { lang: 'en', dir: 'ltr', setLang: () => {}, locales: ${locales} }\n` +
      `}\n`
    )
  }

  const dsImport = input.hasDesignSystem
    ? `import { DesignSystemProvider } from '@alm-design/design-system'\nimport '@alm-design/design-system/dist/index.css'\n`
    : ''

  // The design system resolves direction in JavaScript (`useDir`), so the CSS
  // half (`dir` on <html>) is not enough on its own — a screen comes out
  // half-mirrored, chevrons pointing the wrong way inside a correctly flipped
  // layout. Feeding the language context's own `dir` into the provider is what
  // keeps both halves agreeing.
  const inner = input.hasDesignSystem
    ? `    <DesignSystemProvider platform="ios" dir={dir}>{children}</DesignSystemProvider>`
    : `    children`

  return (
    `${BANNER}import { LanguageProvider, useLanguage } from '../i18n/LanguageContext'\n${dsImport}\n` +
    `/**\n` +
    ` * The project's own language provider, with the design system's direction\n` +
    ` * fed from it. The DS resolves direction in JavaScript, so \`dir\` on <html>\n` +
    ` * alone leaves every mirrored chevron pointing the wrong way.\n` +
    ` */\n` +
    `export function Providers({ children }) {\n` +
    `  return (\n` +
    `    <LanguageProvider>\n` +
    `      <DirectionBridge>{children}</DirectionBridge>\n` +
    `    </LanguageProvider>\n` +
    `  )\n` +
    `}\n\n` +
    `function DirectionBridge({ children }) {\n` +
    `  const { dir } = useLanguage()\n` +
    `  return (\n` +
    `${inner}\n` +
    `  )\n` +
    `}\n\n` +
    `/** The shape App.jsx expects, whether or not this project has i18n. */\n` +
    `export function useShellLanguage() {\n` +
    `  const { lang, dir, setLang } = useLanguage()\n` +
    `  return { lang, dir, setLang, locales: ${locales} }\n` +
    `}\n`
  )
}

/** Both generated files, ready to write. */
export function generatedShellFiles(input: ShellRegistryInput): ShellFile[] {
  return [
    { relPath: `${PROTOTYPE_SHELL_DIR}/registry.generated.jsx`, contents: renderRegistryFile(input) },
    { relPath: `${PROTOTYPE_SHELL_DIR}/providers.generated.jsx`, contents: renderProvidersFile(input) },
  ]
}

/** The project's boards, or an empty file when it has none yet. */
export function readBoardsForShell(dir: string): BoardsFile {
  const file = boardsFilePath(dir)
  if (!existsSync(file)) return { version: 1, boards: [] }
  return parseBoardsFile(readFileSync(file, 'utf8'))
}

/** True when the workspace ships an `i18n/LanguageContext` the shell can mount. */
export function hasLanguageContext(dir: string): boolean {
  return ['tsx', 'jsx', 'ts', 'js'].some((ext) => existsSync(join(dir, 'i18n', `LanguageContext.${ext}`)))
}
