/**
 * runtimeBridgeShellFile — the ALWAYS-rewritten generated file carrying the
 * bundled in-frame runtime bridge (`@core/studio-runtime`'s `runtime.ts`,
 * with `@sinclair/typebox` inlined by `scripts/sync-studio-runtime.ts`).
 *
 * Sibling of `studioRuntimeShellFile.ts`, same reasoning: `main.jsx` is a
 * STATIC (hash-protected, "written once") file, so it only imports this
 * generated module once and is then frozen the moment a user edits it. A fix
 * to `runtime.ts` has to reach an already-scaffolded workspace independent of
 * whether `vite.config.js`/`main.jsx` are still untouched — putting the
 * bundled logic here, rewritten unconditionally on every `ensurePrototypeShell`
 * call, is what makes that possible.
 *
 * Deep import (not through `@core/studio-runtime`'s barrel) for the same
 * reason `studioRuntimeShellFile.ts` deep-imports its own bundle: routing a
 * multi-KB bundled-string artifact through the barrel other admin code
 * imports would defeat the point of keeping it out of the admin bundle.
 * `server/` is never part of the browser bundle, so this costs nothing here.
 */
import { STUDIO_RUNTIME_BRIDGE_SOURCE } from '@core/studio-runtime/generated/runtimeBridgeBundle'
import { PROTOTYPE_SHELL_DIR, type ShellFile } from './shellPaths'

const BANNER = `/* Generated by Studio from src/core/studio-runtime/runtime.ts — do not
 * edit. Rewritten every time the project is opened. The in-frame half of
 * the live-canvas bridge: postMessage dispatch, overlay/selection DOM,
 * optimistic edits. Inert until main.jsx actually constructs it. */
`

/** `prototype/studioRuntimeBridge.generated.js` — see this module's header for why it is always rewritten rather than hash-protected like the rest of `staticShellFiles()`. */
export function runtimeBridgeShellFile(): ShellFile {
  return {
    relPath: `${PROTOTYPE_SHELL_DIR}/studioRuntimeBridge.generated.js`,
    contents: `${BANNER}${STUDIO_RUNTIME_BRIDGE_SOURCE}`,
  }
}
