/**
 * studioRuntimeShellFile — the ALWAYS-rewritten generated file carrying the
 * bundled Vite plugin (`@core/studio-runtime`'s `vitePlugin.ts`, with
 * `@babel/core` inlined by `scripts/sync-studio-runtime.ts`).
 *
 * Unlike `registry.generated.jsx`/`providers.generated.jsx` (rewritten from
 * `.studio/` on every open — see `registryFile.ts`), this file's CONTENT
 * never depends on the workspace at all: it is the same committed string for
 * every project. It still has to be an ALWAYS-rewritten generated file rather
 * than a STATIC (hash-protected) one: `vite.config.js` only imports it once
 * and is then FROZEN the moment a user edits it (see `shellFiles.ts`'s
 * "written once vs kept in step" table), so if the plugin's actual logic
 * lived directly inside `vite.config.js`, a fix to it could never reach a
 * workspace whose config the user has since touched. Putting the logic here
 * instead means every `ensurePrototypeShell` call refreshes it
 * unconditionally, independent of `vite.config.js`'s own freeze state.
 *
 * Deep import (not through `@core/studio-runtime`'s barrel) is deliberate:
 * the barrel exists to keep `idStamp.ts`/`vitePlugin.ts` (and the
 * `@babel/core` they carry) out of the admin bundle, and routing a 2MB
 * bundled-string artifact through that same public API would defeat the
 * point of the exclusion. `server/` is never part of the browser bundle, so
 * this deep import costs nothing there — same precedent as
 * `server/plugins/modulePackVm.ts` importing the QuickJS bootstrap's own
 * generated artifact directly.
 */
import { STUDIO_RUNTIME_VITE_PLUGIN_SOURCE } from '@core/studio-runtime/generated/vitePluginBundle'
import { PROTOTYPE_SHELL_DIR, type ShellFile } from './shellPaths'

const BANNER = `/* Generated by Studio from src/core/studio-runtime/vitePlugin.ts — do not
 * edit. Rewritten every time the project is opened. Stamps every host JSX
 * element with a data-node-id Studio's canvas can match back to the source
 * position it came from. vite.config.js imports this file. */
`

/** `prototype/studioRuntime.generated.js` — see this module's header for why it is always rewritten rather than hash-protected like the rest of `staticShellFiles()`. */
export function studioRuntimeShellFile(): ShellFile {
  return {
    relPath: `${PROTOTYPE_SHELL_DIR}/studioRuntime.generated.js`,
    contents: `${BANNER}${STUDIO_RUNTIME_VITE_PLUGIN_SOURCE}`,
  }
}
