import { DATA_COMPONENT_ATTR, DATA_DYNAMIC_ATTR, findByUid } from './dom.js';

/**
 * FP-4a (`.orchestrator/FEATURE-PARITY-PLAN.md` §2 FP-4, "in-place text
 * editing" bullet) — runs INSIDE the file-app iframe (this whole package
 * does; see `bridge.ts`'s module doc). Turns one `data-uid` node
 * `contentEditable` on `enter-text-edit`, and autonomously ends the edit on
 * Enter (commit), blur (commit), or Esc (cancel/restore) — no further
 * studio->bridge message is needed to end an edit; the bridge always
 * reports the outcome unsolicited via `onExit` (wired to the
 * `text-edit-exit` bridge->studio message in `bridge.ts`).
 *
 * Penpot-fidelity note (per this task's brief): the INTERACTION FEEL here —
 * double-click to enter, Enter/blur commits, Esc cancels and restores the
 * original text, click-out (blur) commits — is taken from Penpot's real
 * text editor UX (`frontend/src/app/main/ui/workspace/shapes/text/
 * editor.cljs` + `v2_editor.cljs`: `handle-key-down` treats `Esc` as
 * "discard changes, exit"; blur commits via the same path a normal edit-
 * session end takes). The IMPLEMENTATION is deliberately NOT Penpot's vector
 * text-shape engine (§7 code-first adaptation) — this is plain DOM
 * `contentEditable` on a real rendered JSX element, because our "text" is
 * genuine React/DOM content, not a drawn vector shape.
 *
 * Editable-surface contract (playbook §0, reused verbatim from the P2/P3
 * dynamic-lock): a node is a valid contentEditable target only if it is
 * (a) not `dynamic` (generated by `.map()`/conditional — real code, not
 * editable here), (b) not a component-instance usage site (`data-component`
 * present — editing a `<Button>Label</Button>` usage's rendered text isn't
 * the same as editing the component's own source), and (c) a genuine text
 * LEAF: an element with no tagged (or any) element children, so replacing
 * `textContent` can't silently eat nested markup/child elements. This is a
 * deliberate, disclosed simplification (mirrors `Inspector.tsx`'s
 * `ContentSection`, which likewise does a flat text replace) — rich mixed
 * content (`<p>Hello <strong>world</strong></p>`) is out of scope for FP-4a
 * in-place editing; the Content section in the Inspector remains the way to
 * retext such nodes.
 */

const EDITING_CLASS = 'ccs-bridge-editing';
const STYLE_ELEMENT_ID = 'ccs-bridge-text-edit-style';

/** Elements that can never sensibly hold text content, even if they somehow
 * carry a `data-uid` with no element children (defensive; in practice these
 * tags' own JSX usage wouldn't have text children to begin with). */
const VOID_TAGS = new Set(['img', 'input', 'br', 'hr', 'svg', 'video', 'canvas', 'iframe']);

export type TextEditRejectReason =
  | 'already-editing'
  | 'not-found'
  | 'dynamic-locked'
  | 'component-instance'
  | 'not-a-text-leaf'
  | 'void-element';

export type TextEditEnterResult = { ok: true; text: string } | { ok: false; reason: TextEditRejectReason };

export interface TextEditExitResult {
  uid: string;
  committed: boolean;
  /** The committed text, or `null` when cancelled (Esc) — the DOM has
   * already been restored to `originalText` in that case. */
  text: string | null;
}

export interface TextEditController {
  /** Attempts to enter edit mode on `uid`. See {@link TextEditRejectReason}
   * for every rejection case. Only one node can be edited at a time. */
  enter(uid: string, doc?: Document): TextEditEnterResult;
  /** Ends whatever edit is in progress (if any) — `commit: true` reads the
   * live DOM text; `commit: false` restores the original text first. A
   * no-op (returns `null`) if nothing is being edited. Also invoked
   * internally by the controller's own Enter/blur/Esc listeners. */
  exit(commit: boolean): TextEditExitResult | null;
  /** The uid currently being edited, or `null`. */
  currentUid(): string | null;
}

function ensureStyle(doc: Document): void {
  if (doc.getElementById(STYLE_ELEMENT_ID)) return;
  const style = doc.createElement('style');
  style.id = STYLE_ELEMENT_ID;
  style.textContent = `.${EDITING_CLASS} { outline: 2px solid #f59e0b !important; outline-offset: -1px; cursor: text; }`;
  doc.head.appendChild(style);
}

/** Selects the element's full text content — a quick-overwrite UX nicety
 * (Penpot's own text editor selects existing content on entry) rather than
 * leaving the caret at a browser-default position. Best-effort: swallows
 * any Selection API failure (e.g. a test document without a real
 * `getSelection`/`Range` implementation) since it's cosmetic, never
 * required for the edit to function. */
function selectAllContent(el: HTMLElement, win: Window): void {
  try {
    const range = win.document.createRange();
    range.selectNodeContents(el);
    const selection = win.getSelection?.();
    selection?.removeAllRanges();
    selection?.addRange(range);
  } catch {
    // cosmetic only — see doc comment above.
  }
}

function isTextLeaf(el: HTMLElement): boolean {
  return el.children.length === 0;
}

/** Constructs a fresh controller. `onExit` fires exactly once per
 * `enter()`/exit cycle (Enter, blur, or Esc — never more than once per
 * edit), whether the edit was committed or cancelled. `win` is injectable
 * for tests (defaults to the real global `window`), matching every other
 * module in this package. */
export function createTextEditController(
  onExit: (result: TextEditExitResult) => void,
  win: Window = window,
): TextEditController {
  let editingUid: string | null = null;
  let editingEl: HTMLElement | null = null;
  let originalText = '';

  function handleKeydown(e: KeyboardEvent): void {
    if (e.key === 'Escape') {
      e.preventDefault();
      exit(false);
    } else if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      exit(true);
    }
  }

  function handleBlur(): void {
    exit(true);
  }

  function detachListeners(el: HTMLElement): void {
    el.removeEventListener('keydown', handleKeydown);
    el.removeEventListener('blur', handleBlur);
  }

  function enter(uid: string, doc: Document = win.document): TextEditEnterResult {
    if (editingUid) return { ok: false, reason: 'already-editing' };

    const el = findByUid(doc, uid);
    if (!el) return { ok: false, reason: 'not-found' };
    if (el.getAttribute(DATA_DYNAMIC_ATTR) === 'true') return { ok: false, reason: 'dynamic-locked' };
    if (el.hasAttribute(DATA_COMPONENT_ATTR)) return { ok: false, reason: 'component-instance' };
    if (VOID_TAGS.has(el.tagName.toLowerCase())) return { ok: false, reason: 'void-element' };
    if (!isTextLeaf(el)) return { ok: false, reason: 'not-a-text-leaf' };

    ensureStyle(doc);
    originalText = el.textContent ?? '';
    editingUid = uid;
    editingEl = el;

    el.setAttribute('contenteditable', 'true');
    el.classList.add(EDITING_CLASS);
    el.addEventListener('keydown', handleKeydown);
    el.addEventListener('blur', handleBlur);
    el.focus();
    selectAllContent(el, win);

    return { ok: true, text: originalText };
  }

  function exit(commit: boolean): TextEditExitResult | null {
    if (!editingUid || !editingEl) return null;
    const uid = editingUid;
    const el = editingEl;

    detachListeners(el);
    const finalText = commit ? (el.textContent ?? '') : originalText;
    if (!commit) el.textContent = originalText;
    el.removeAttribute('contenteditable');
    el.classList.remove(EDITING_CLASS);

    editingUid = null;
    editingEl = null;
    originalText = '';

    const result: TextEditExitResult = { uid, committed: commit, text: commit ? finalText : null };
    onExit(result);
    return result;
  }

  return {
    enter,
    exit,
    currentUid: () => editingUid,
  };
}
