/**
 * classAssignmentUnsavedNotice — Phase 0 item 0.6's honesty fix, now scoped
 * to the genuinely unwritable case.
 *
 * Track B2 gave Studio a real `kind: 'class'` edit (`setJsxClassName`,
 * `server/handlers/studioEditSchemas.ts`) — `classNameWriteback.ts`'s
 * `collectClassNameEdits` diffs `PageNode.classIds` against the load-time
 * baseline (`loadedValuesBaseline.ts`) and sends most class assignments to
 * disk on the next `saveSite`. What CANNOT be sent is a node with no writable
 * source location at all — a `.map` row (one piece of JSX renders every row)
 * or a synthetic root (`index:body`) — because there is no single honest
 * place a `className` edit could land. This module is that residual warning,
 * called from `fsCodemodAdapter.saveSite` with exactly that subset, at the
 * moment the write would have been attempted (had there been anywhere to aim
 * it), for every node affected since the last save — including drift from a
 * non-UI path (e.g. an AI-agent edit).
 *
 * See STUDIO-FIGMA-PARITY-PLAN.md item 0.6 (the original honesty-only
 * stopgap) and §5 Track B2 (the write this module now sits downstream of).
 */
import { pushToast } from '@ui/components/Toast'
import { isStudioMode } from '@site/studio/studioMode'

/** One node's resolved class drift, ready to render — ids already turned into display names by the caller (`classNameWriteback.ts`'s `collectClassNameEdits`), which has the registry and `site.styleRules` in scope. */
export interface ClassAssignmentDriftDetail {
  nodeLabel: string
  addedClassNames: readonly string[]
  removedClassNames: readonly string[]
  reordered: boolean
}

function describeDrift(detail: ClassAssignmentDriftDetail): string {
  const parts: string[] = []
  if (detail.addedClassNames.length > 0) parts.push(`added ${detail.addedClassNames.join(', ')}`)
  if (detail.removedClassNames.length > 0) parts.push(`removed ${detail.removedClassNames.join(', ')}`)
  if (detail.reordered) parts.push('reordered classes')
  return parts.length > 0 ? `${detail.nodeLabel} (${parts.join(', ')})` : detail.nodeLabel
}

const MAX_NAMED = 3

/**
 * Warn that class assignment drift on one or more nodes has NO writable
 * source location at all, so it cannot survive a save + reload in Studio
 * mode no matter what `setJsxClassName` can write elsewhere. No-ops outside
 * Studio mode (where `classIds` DOES persist, as a `data_rows` CMS record)
 * and on an empty list — mirrors every other refusal/skip toast in this
 * codebase.
 */
export function notifyClassAssignmentUnsaved(drifts: readonly ClassAssignmentDriftDetail[]): void {
  if (!isStudioMode()) return
  if (drifts.length === 0) return

  const named = drifts.slice(0, MAX_NAMED).map(describeDrift)
  const remaining = drifts.length - named.length
  const list = remaining > 0 ? `${named.join('; ')}; and ${remaining} more` : named.join('; ')

  pushToast({
    kind: 'warning',
    title: "Class change won't be saved",
    body:
      `${list}. This element has no single place in your source to write a class change to ` +
      `(it's generated by a loop, or has no source location at all) — ` +
      `${drifts.length === 1 ? 'it' : 'these'} will revert the next time this page loads.`,
    location: 'site-editor',
  })
}
