/**
 * Builds a `ComponentManifest` for `@alm-design/design-system` FROM the
 * package's own catalog module (`<pkgRoot>/mcp/catalog.js`) — not from local
 * files and not from `react-docgen`. The catalog is generated by the design
 * system itself from its source-of-truth docs (`CLAUDE.md` / `design.md` /
 * `src/index.js`), so it's the most reliable list of public components and
 * their real usage.
 *
 * NOTE on `ComponentSpec.file`: for package-sourced components there is no
 * local file to point at, so `file` holds the bare import specifier
 * (`'@alm-design/design-system'`) that a consumer would actually import
 * from — not a filesystem path.
 */
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { pathToFileURL } from 'node:url'
import type { ComponentManifest, ComponentSpec, PropSpec, PropSpecKind } from '../component-manifest/types'

const PACKAGE_NAME = '@alm-design/design-system'
const FILE_SPECIFIER = PACKAGE_NAME

/** Shape of the subset of `mcp/catalog.js`'s exports we rely on. */
interface DesignSystemCatalog {
  componentNames: string[]
  propsFor(name: string): string[] | null
  apiDoc(name: string): string | null
}

/**
 * Matches a JSX usage-example line like:
 *   size="regular"         // regular | small
 * Group 1 is the prop name, group 2 is the raw comment text after `//`.
 * The lazy `.*?` before `//` means we don't try to parse the prop's value
 * (which may itself contain braces/slashes, e.g. `leadingIcon={<Icon />}`)
 * — we just need the first `//` after the `propName=` to locate the comment.
 */
const ENUM_COMMENT_LINE = /^([A-Za-z_$][A-Za-z0-9_$]*)=.*?\/\/\s*(.+)$/

/**
 * Best-effort extraction of enum values per prop from a component's API doc.
 * Parses the first fenced code block (the JSX usage example) line by line;
 * for any line matching `propName=... // a | b | c`, splits the comment on
 * `|` and keeps the trimmed, non-empty tokens if there are at least two.
 * Never throws — returns an empty map for anything it can't parse.
 */
function parseEnumValues(doc: string | null): Map<string, string[]> {
  const enums = new Map<string, string[]>()
  if (!doc) return enums

  const block = /```[a-z]*\n([\s\S]*?)```/i.exec(doc)
  if (!block) return enums

  for (const rawLine of block[1].split('\n')) {
    const line = rawLine.trim()
    const match = ENUM_COMMENT_LINE.exec(line)
    if (!match) continue

    const [, propName, commentText] = match
    const tokens = commentText
      .split('|')
      .map((token) => token.trim())
      .filter((token) => token.length > 0)
      // Reduce each token to just its value: the substring before the first
      // whitespace or `(`. Drops trailing prose/annotations (e.g. "default
      // (48px)" -> "default", "rtl — via useDir; ..." -> "rtl") while
      // leaving hyphenated values with no space/paren intact (e.g.
      // "primary-inverted", "gpay-pay-with").
      .map((token) => token.split(/[\s(]/)[0])
      .filter((token) => token.length > 0)

    // Drop duplicate tokens (can arise after cleaning, e.g. two prose
    // variants of the same base value) while preserving first-seen order.
    const uniqueTokens = [...new Set(tokens)]

    if (uniqueTokens.length >= 2) {
      enums.set(propName, uniqueTokens)
    }
  }

  return enums
}

/** Resolves the installed package's root directory. */
function resolvePackageRoot(): string {
  try {
    const require = createRequire(import.meta.url)
    return dirname(require.resolve(`${PACKAGE_NAME}/package.json`))
  } catch {
    return join(process.cwd(), 'node_modules', PACKAGE_NAME)
  }
}

/**
 * Matches a JSX usage-example line's prop NAME and raw VALUE:
 *   skeleton={false}       // renders a shimmer
 *   icon={<SvgIcon />}
 *   bg="default"           // default | primary | dim
 * Group 2 is everything after `=` up to a trailing `//` comment (which
 * `ENUM_COMMENT_LINE` above parses separately). Deliberately greedy up to the
 * comment so a braced value containing `/` (`<Icon a="b/c"/>`) survives.
 */
const PROP_VALUE_LINE = /^([A-Za-z_$][A-Za-z0-9_$]*)=(.*?)(?:\s*\/\/.*)?$/

/**
 * The prop kinds this package's docs can express, read off the VALUE FORM in
 * each component's JSX example. Nothing here guesses from the prop's NAME
 * except the icon/node distinction, which is a presentation choice (both are
 * React nodes; an icon-named one gets a picker instead of a bare slot).
 *
 * A form this does not recognise — a structured `{[…]}` array, a `{{…}}`
 * object, an interpolation — returns `undefined` rather than a wrong answer,
 * and the prop keeps whatever the enum pass gave it (or falls through to
 * `'unknown'`, i.e. a text box). That is the honest failure mode: a text box
 * for a value we could not classify, never a toggle for something that is not
 * a boolean.
 */
function classifyPropValue(propName: string, rawValue: string): PropSpecKind | undefined {
  const value = rawValue.trim()
  if (value === '') return undefined

  // `prop` with no `=` in JSX means `prop={true}`; the docs write it out.
  if (/^\{(true|false)\}$/.test(value)) return 'boolean'
  if (/^\{-?\d+(\.\d+)?\}$/.test(value)) return 'number'
  // `{fn}`, `{() => …}`, `{handleX}` — a callback. Never editable: a text box
  // here can only write a string where the component expects a function.
  if (/^\{(fn|\(\)\s*=>|\w*[Hh]andler\b|on[A-Z])/.test(value) || /^on[A-Z]/.test(propName)) return 'handler'
  if (/^\{\s*</.test(value)) return ICON_PROP_NAME_RE.test(propName) ? 'icon' : 'node'
  if (/^["']/.test(value)) return 'string'
  return undefined
}

/** A prop whose node value is an ICON rather than arbitrary content — it gets the icon picker instead of a generic slot row. */
const ICON_PROP_NAME_RE = /(^|[a-z])icon([A-Z0-9]|$)/i

/** Prop name -> raw documented value, from the first fenced JSX block. Same block `parseEnumValues` reads. */
function parsePropValues(doc: string | null): Map<string, string> {
  const values = new Map<string, string>()
  if (!doc) return values
  const block = /```[a-z]*\n([\s\S]*?)```/i.exec(doc)
  if (!block) return values
  for (const rawLine of block[1].split('\n')) {
    const match = PROP_VALUE_LINE.exec(rawLine.trim())
    if (!match) continue
    const [, propName, rawValue] = match
    if (!values.has(propName)) values.set(propName, rawValue)
  }
  return values
}

function buildProps(name: string, catalog: DesignSystemCatalog): PropSpec[] {
  let propNames: string[] | null
  try {
    propNames = catalog.propsFor(name)
  } catch {
    propNames = null
  }

  let doc: string | null
  try {
    doc = catalog.apiDoc(name)
  } catch {
    doc = null
  }

  const enumValues = parseEnumValues(doc)
  const propValues = parsePropValues(doc)

  return (propNames ?? []).map((propName): PropSpec => {
    const spec: PropSpec = {
      name: propName,
      tsType: 'unknown',
      required: false,
    }
    const values = enumValues.get(propName)
    if (values) {
      spec.enumValues = values
    }
    // An enum beats the value form: `bg="default" // default | primary | dim`
    // reads as a plain string by shape, and the comment is what says it is a
    // closed set. Everything else takes the form's answer.
    const kind = values ? 'enum' : classifyPropValue(propName, propValues.get(propName) ?? '')
    if (kind) spec.kind = kind
    return spec
  })
}

export async function buildDesignSystemManifest(): Promise<ComponentManifest> {
  const pkgRoot = resolvePackageRoot()
  const catalogUrl = pathToFileURL(join(pkgRoot, 'mcp/catalog.js')).href
  const catalog = (await import(catalogUrl)) as DesignSystemCatalog

  const components: ComponentSpec[] = catalog.componentNames.map((name) => ({
    name,
    file: FILE_SPECIFIER,
    exportName: name,
    isDefaultExport: false,
    props: buildProps(name, catalog),
  }))

  return { components }
}
