/**
 * Builds a `ComponentManifest` for `@alm-design/design-system` FROM the
 * package's own catalog module (`<pkgRoot>/mcp/catalog.js`) — not from local
 * files and not from `react-docgen`. The catalog is generated by the design
 * system itself from its source-of-truth docs (`CLAUDE.md` / `design.md` /
 * `src/index.js`), so it's the most reliable list of public components and
 * their real usage.
 *
 * NOTE on `ComponentSpec.file`: for package-sourced components there is no
 * local file to point at, so `file` holds the bare import specifier
 * (`'@alm-design/design-system'`) that a consumer would actually import
 * from — not a filesystem path.
 */
import { readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { pathToFileURL } from 'node:url'
import type { ComponentManifest, ComponentSpec, PropSpec, PropSpecKind } from '../component-manifest/types'

const PACKAGE_NAME = '@alm-design/design-system'
const FILE_SPECIFIER = PACKAGE_NAME

/** Shape of the subset of `mcp/catalog.js`'s exports we rely on. */
interface DesignSystemCatalog {
  componentNames: string[]
  propsFor(name: string): string[] | null
  apiDoc(name: string): string | null
}

/**
 * Matches a JSX usage-example line like:
 *   size="regular"         // regular | small
 * Group 1 is the prop name, group 2 is the raw comment text after `//`.
 * The lazy `.*?` before `//` means we don't try to parse the prop's value
 * (which may itself contain braces/slashes, e.g. `leadingIcon={<Icon />}`)
 * — we just need the first `//` after the `propName=` to locate the comment.
 */
const ENUM_COMMENT_LINE = /^([A-Za-z_$][A-Za-z0-9_$]*)=.*?\/\/\s*(.+)$/

/**
 * See the call site in {@link parseEnumValues} for why this is not "everything
 * before the first space".
 *
 * The leading `scope:` strip handles `AdBanner`'s `// mobile only: small (row) |
 * medium | large` — the first option is `small`, and the prose in front of it
 * names which layout the whole list applies to.
 */
function stripEnumAnnotation(token: string): string {
  const scoped = token.replace(/^[^:]*:\s*/, '')
  const value = scoped.split(/[(—–;]/)[0]!.trim()
  const words = value.split(/\s+/)
  return words.length > 3 ? words[0]! : value
}

/**
 * Best-effort extraction of enum values per prop from a component's API doc.
 * Parses the first fenced code block (the JSX usage example) line by line;
 * for any line matching `propName=... // a | b | c`, splits the comment on
 * `|` and keeps the trimmed, non-empty tokens if there are at least two.
 * Never throws — returns an empty map for anything it can't parse.
 */
function parseEnumValues(doc: string | null): Map<string, string[]> {
  const enums = new Map<string, string[]>()
  if (!doc) return enums

  const block = /```[a-z]*\n([\s\S]*?)```/i.exec(doc)
  if (!block) return enums

  for (const rawLine of block[1].split('\n')) {
    const line = rawLine.trim()
    const match = ENUM_COMMENT_LINE.exec(line)
    if (!match) continue

    const [, propName, commentText] = match
    const tokens = commentText
      .split('|')
      .map((token) => token.trim())
      .filter((token) => token.length > 0)
      // Reduce each token to just its value by stripping the ANNOTATION forms
      // this package writes — a parenthetical, and anything after an em/en dash
      // or a semicolon: "default (48px)" -> "default", "rtl — via useDir; …" ->
      // "rtl". It used to cut at the first whitespace instead, which is the
      // same thing for every single-word value and wrong for a multi-word one:
      // `Separator`'s `type="cell separator" // cell separator (default) |
      // section separator` became `cell` / `section`, so the panel offered two
      // values the component does not accept and an insert wrote one of them
      // into the user's source. Falls back to the first word for a token that
      // still reads as prose (>3 words), which is what the old rule was
      // defending against.
      .map((token) => stripEnumAnnotation(token))
      .filter((token) => token.length > 0)

    // Drop duplicate tokens (can arise after cleaning, e.g. two prose
    // variants of the same base value) while preserving first-seen order.
    const uniqueTokens = [...new Set(tokens)]

    if (uniqueTokens.length >= 2) {
      enums.set(propName, uniqueTokens)
    }
  }

  return enums
}

/** Resolves the installed package's root directory. */
function resolvePackageRoot(): string {
  try {
    const require = createRequire(import.meta.url)
    return dirname(require.resolve(`${PACKAGE_NAME}/package.json`))
  } catch {
    return join(process.cwd(), 'node_modules', PACKAGE_NAME)
  }
}

/**
 * Matches a JSX usage-example line's prop NAME and raw VALUE:
 *   skeleton={false}       // renders a shimmer
 *   icon={<SvgIcon />}
 *   bg="default"           // default | primary | dim
 * Group 2 is everything after `=` up to a trailing `//` comment (which
 * `ENUM_COMMENT_LINE` above parses separately). Deliberately greedy up to the
 * comment so a braced value containing `/` (`<Icon a="b/c"/>`) survives.
 */
const PROP_VALUE_LINE = /^([A-Za-z_$][A-Za-z0-9_$]*)=(.*?)(?:\s*\/\/.*)?$/

/**
 * The prop kinds this package's docs can express, read off the VALUE FORM in
 * each component's JSX example. Nothing here guesses from the prop's NAME
 * except the icon/node distinction, which is a presentation choice (both are
 * React nodes; an icon-named one gets a picker instead of a bare slot).
 *
 * A form this does not recognise — a structured `{[…]}` array, a `{{…}}`
 * object, an interpolation — returns `undefined` rather than a wrong answer,
 * and the prop keeps whatever the enum pass gave it (or falls through to
 * `'unknown'`, i.e. a text box). That is the honest failure mode: a text box
 * for a value we could not classify, never a toggle for something that is not
 * a boolean.
 */
function classifyPropValue(propName: string, rawValue: string): PropSpecKind | undefined {
  const value = rawValue.trim()
  if (value === '') return undefined

  // `prop` with no `=` in JSX means `prop={true}`; the docs write it out.
  if (/^\{(true|false)\}$/.test(value)) return 'boolean'
  if (/^\{-?\d+(\.\d+)?\}$/.test(value)) return 'number'
  // `{fn}`, `{() => …}`, `{handleX}` — a callback. Never editable: a text box
  // here can only write a string where the component expects a function.
  if (/^\{(fn|\(\)\s*=>|\w*[Hh]andler\b|on[A-Z])/.test(value) || /^on[A-Z]/.test(propName)) return 'handler'
  if (/^\{\s*</.test(value)) return ICON_PROP_NAME_RE.test(propName) ? 'icon' : 'node'
  if (/^["']/.test(value)) return 'string'
  // A structured `{[…]}` / `{{…}}` value. This used to return `undefined` and
  // fall through to a text box, which the module doc above called the honest
  // failure mode — and it is not. A text box on `items={[{ icon, label }]}`
  // accepts anything and every value it accepts is wrong: typing `5` reached
  // `items.map(...)` and rendered "TabBar (render error)". Naming the shape
  // lets the panel decline the edit instead of inviting a broken one.
  if (/^\{\s*[[{]/.test(value)) return 'collection'
  return undefined
}

/** A prop whose node value is an ICON rather than arbitrary content — it gets the icon picker instead of a generic slot row. */
const ICON_PROP_NAME_RE = /(^|[a-z])icon([A-Z0-9]|$)/i

/**
 * A string prop naming an IMAGE the user supplies: `imageSrc`,
 * `partnerLogoSrc`, `cardArt`, `avatarUrl`.
 *
 * These are documented as plain strings (`imageSrc="/transfer.jpg"`), so the
 * value-form pass classifies them `'string'` and the panel renders a text box
 * — asking a designer to type a path to a file they have not uploaded
 * anywhere. The image control has an upload affordance AND still accepts a
 * URL, so it is a strict superset of what the text box could do.
 *
 * Matched on the name because that is the only signal the docs carry: a URL
 * and a label are the same shape. The image word must END the name — an
 * earlier version matched it anywhere and classified `imageActionLabel` (a
 * LABEL) as an image. `iconSrc` is deliberately excluded: an icon prop
 * already has its own richer picker.
 */
const IMAGE_PROP_NAME_RE = /(src|image|logo|photo|avatar|thumbnail|poster|banner|art)$/i

/** Whether `propName` names an image source — see {@link IMAGE_PROP_NAME_RE}. */
function isImageProp(propName: string): boolean {
  if (ICON_PROP_NAME_RE.test(propName)) return false
  return IMAGE_PROP_NAME_RE.test(propName)
}

/**
 * The FIRST usage example in a component's fenced doc block.
 *
 * Several components document more than one usage in a single fence, and the
 * examples are ALTERNATIVES, not one combined call. `Dialog` writes an iOS
 * example (`primaryAction`/`destructiveAction`/`secondaryAction`) followed by an
 * Android one (`action1`/`action2`); reading the whole fence seeded all five,
 * so an inserted iOS dialog arrived carrying two Android-only buttons. `Badge`
 * documents `variant="alert" count={5}` and then `variant="new"`, which
 * contradict each other outright.
 *
 * Cut at the end of the first top-level element rather than at a blank line:
 * `Navbar`'s single example is full of blank lines and section comments INSIDE
 * its `toolbar={{ … }}` object, and a blank-line rule truncated it to three
 * props — which cost the component its `chips` and `segmentedControl` and drew
 * an empty bar, the exact defect this pass exists to end. Brace/bracket depth is
 * what distinguishes "still inside the call" from "a second example".
 */
function firstUsageExample(block: string): string {
  const open = /<([A-Z][\w]*)/.exec(block)
  if (!open) return block
  const name = open[1]!
  let depth = 0
  let quote = ''
  for (let i = open.index + open[0].length; i < block.length; i++) {
    const ch = block[i]!
    if (quote) {
      if (ch === quote) quote = ''
      continue
    }
    if (ch === '"' || ch === "'") quote = ch
    else if (ch === '{' || ch === '[') depth++
    else if (ch === '}' || ch === ']') depth--
    else if (ch === '>' && depth === 0) {
      // `<Badge … />` ends here; `<Dialog …>` continues to its closing tag.
      if (block[i - 1] === '/') return block.slice(0, i + 1)
      const close = block.indexOf(`</${name}>`, i)
      return close === -1 ? block : block.slice(0, close + name.length + 3)
    }
  }
  return block
}

/**
 * Prop name -> the trailing `//` comment on its documented line.
 *
 * The same comment {@link parseEnumValues} reads for a pipe list, kept whole
 * here because it also carries prose facts about the prop —
 * `value={0}  // active tab index (0-based, controlled)` is what says `value`
 * indexes a collection rather than being a free number.
 */
function parsePropComments(doc: string | null): Map<string, string> {
  const comments = new Map<string, string>()
  if (!doc) return comments
  const block = /```[a-z]*\n([\s\S]*?)```/i.exec(doc)
  if (!block) return comments
  for (const rawLine of firstUsageExample(block[1]!).split('\n')) {
    const match = ENUM_COMMENT_LINE.exec(rawLine.trim())
    if (match && !comments.has(match[1]!)) comments.set(match[1]!, match[2]!)
  }
  return comments
}

/**
 * A prop written inline among others on one line: `variant="alert" count={5}`.
 * Values are non-greedy and brace-flat on purpose — this pass exists for the
 * short scalar forms {@link PROP_VALUE_LINE} cannot reach, and a nested
 * structure is {@link parsePropLiterals}' job.
 */
const INLINE_PROP_VALUE = /\b([A-Za-z_$][\w$]*)=("[^"]*"|'[^']*'|\{[^{}\n]*\})/g

/** Prop name -> raw documented value, from the first fenced JSX block. Same block `parseEnumValues` reads. */
function parsePropValues(doc: string | null): Map<string, string> {
  const values = new Map<string, string>()
  if (!doc) return values
  const block = /```[a-z]*\n([\s\S]*?)```/i.exec(doc)
  if (!block) return values
  const example = firstUsageExample(block[1]!)
  for (const rawLine of example.split('\n')) {
    const match = PROP_VALUE_LINE.exec(rawLine.trim())
    if (!match) continue
    const [, propName, rawValue] = match
    if (!values.has(propName)) values.set(propName, rawValue)
  }
  // Gap-fill from props written INLINE, several to a line. The line pass above
  // needs one prop per line — its regex is anchored at both ends so the trailing
  // `//` comment carrying the enum list is not swallowed into the value — so a
  // component documented as a one-liner yielded NO values at all. Measured:
  // `<Badge variant="alert" count={5} max={99} />` left all three props
  // unclassified (a text box each) and unseeded, so an inserted Badge was an
  // empty pip forever. Gap-fill rather than replace: where the line pass found
  // a value it is the better one, because it alone spans a multi-line literal.
  for (const [, propName, rawValue] of example.matchAll(INLINE_PROP_VALUE)) {
    if (!values.has(propName!)) values.set(propName!, rawValue!)
  }
  return values
}

/**
 * The BALANCED text of every `prop={…}` value in the component's usage example.
 *
 * `parsePropValues` above is line-based, which is right for the scalars it was
 * written for but truncates a multi-line `items={[…]}` to the two characters
 * `{[`. That was enough to CLASSIFY the prop as a collection and stop the panel
 * offering a text box for it, and not enough to do anything useful with the
 * value — so an inserted `<TabBar/>` rendered an empty pill that nothing in the
 * UI could fill. This reads the whole literal.
 */
function parsePropLiterals(doc: string | null): Map<string, string> {
  const out = new Map<string, string>()
  if (!doc) return out
  const block = /```[a-z]*\n([\s\S]*?)```/i.exec(doc)
  if (!block) return out
  const text = firstUsageExample(block[1]!)
  const opener = /([A-Za-z_$][\w$]*)=\{/g
  let match: RegExpExecArray | null
  while ((match = opener.exec(text))) {
    let depth = 1
    let i = match.index + match[0].length
    for (; i < text.length && depth > 0; i++) {
      const ch = text[i]
      if (ch === '{' || ch === '[') depth++
      else if (ch === '}' || ch === ']') depth--
    }
    if (depth === 0 && !out.has(match[1]!)) out.set(match[1]!, text.slice(match.index + match[0].length, i - 1).trim())
  }
  return out
}

/**
 * A documented JS literal turned into a plain JSON value, or `undefined` when
 * it cannot be turned into one honestly.
 *
 * The docs are written for humans, so the literals carry things JSON has no
 * room for: `onClick: fn` placeholders, `<HomeIcon />` elements, `/* … *\/`
 * elisions. Each is DROPPED rather than guessed at — a tab keeps its `label`
 * and loses its `icon`, which renders a real, labelled tab bar instead of
 * nothing. Anything left unparseable yields `undefined` and the prop simply
 * gets no default, exactly as before.
 */
function exampleFromLiteral(raw: string): unknown {
  const cleaned = raw
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/\/\/[^\n]*/g, '')
    // `icon: <HomeIcon />` and bare `<img … />` — a React element cannot survive
    // into JSON, and inventing a stand-in would put a glyph in the user's source
    // that their own docs never asked for.
    .replace(/[A-Za-z_$][\w$]*\s*:\s*<[^<>]*?\/>\s*,?/g, '')
    .replace(/<[^<>]*?\/>\s*,?/g, '')
    // `onClick: fn` — the docs' placeholder for a callback.
    .replace(/([{,]\s*)[A-Za-z_$][\w$]*\s*:\s*(?!true\b|false\b|null\b)[A-Za-z_$][\w$]*\s*(?=[,}])/g, '$1')
    .replace(/…/g, '')
    .replace(/([{,]\s*)([A-Za-z_$][\w$]*)\s*:/g, '$1"$2":')
    .replace(/'([^']*)'/g, '"$1"')
    .replace(/,(\s*[}\]])/g, '$1')
  let parsed: unknown
  try {
    parsed = JSON.parse(cleaned)
  } catch {
    return undefined
  }
  return withContent(parsed)
}

/** Strips what stripping the un-JSON-able parts left behind: an example is only worth seeding if something survived. */
function withContent(value: unknown): unknown {
  if (Array.isArray(value)) {
    const kept = value.filter((item) => withContent(item) !== undefined)
    return kept.length > 0 ? kept : undefined
  }
  if (value !== null && typeof value === 'object') {
    return Object.keys(value).length > 0 ? value : undefined
  }
  if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') return value
  return undefined
}

/**
 * A single-line documented scalar literal (`title="Title"`, `value={40}`,
 * `icon={true}`) as a plain JSON value.
 *
 * The counterpart to {@link exampleFromLiteral}, which reads the balanced
 * multi-line `{[…]}` forms. Split because the two are parsed from different
 * passes — `parsePropValues` is line-based and right for scalars,
 * `parsePropLiterals` is brace-balanced and right for structures.
 *
 * `image` is deliberately absent even though the docs write one
 * (`imageSrc="/transfer.jpg"`): that path names an asset the user's project
 * does not have, so seeding it would put a guaranteed-broken `src` into their
 * source. A blank image slot is the honest state. `icon`/`node` cannot survive
 * into JSON at all, `handler` must never be a value, and `enum` is already
 * seeded from its documented option list.
 */
function documentedScalarExample(
  propName: string,
  kind: PropSpecKind | undefined,
  rawValue: string | undefined,
): unknown {
  if (rawValue === undefined) return undefined
  // Every asset path in these docs (`imageSrc="/photo.jpg"`, `iconSrc="/icon.png"`)
  // names a file the user's project does not have. Matched by NAME rather than
  // by `kind`, because `isImageProp` deliberately hands the icon-named ones to
  // the icon picker instead — which leaves them `kind: 'string'`, and seeding a
  // string is exactly how `/icon.png` would reach their source.
  if (IMAGE_PROP_NAME_RE.test(propName)) return undefined
  const value = rawValue.trim()
  switch (kind) {
    case 'string': {
      const quoted = /^(["'])([\s\S]*)\1$/.exec(value)
      return quoted?.[2] === undefined || quoted[2] === '' ? undefined : quoted[2]
    }
    case 'number': {
      const braced = /^\{\s*(-?\d+(?:\.\d+)?)\s*\}$/.exec(value)
      return braced ? Number(braced[1]) : undefined
    }
    case 'boolean': {
      const braced = /^\{\s*(true|false)\s*\}$/.exec(value)
      return braced ? braced[1] === 'true' : undefined
    }
    default:
      return undefined
  }
}

/**
 * The value this package's own docs show for `propName`, in whatever form the
 * prop's kind is written in — or `undefined` when the docs show nothing that
 * can honestly become JSON.
 *
 * This used to run for COLLECTIONS ONLY, on the reasoning that "every other
 * kind already has an editable control, so a default from the docs would
 * silently overwrite what the panel offers." That reasoning was measured wrong.
 * A component's content lives in its scalar props — `SystemBanner`'s `title`
 * and `description`, `Snackbar`'s `message`, `Tooltip`'s `content`,
 * `LinearProgressIndicator`'s `value`, `ProgressStepper`'s `steps` — and
 * seeding none of them meant inserting the component drew an EMPTY shell: a
 * bare tinted row, a grey track, a pill with nothing in it. Nothing was
 * overwritten, because there was nothing there; the author was handed a blank
 * box and no clue which of eleven props would make it visible.
 *
 * It is the same defect `TabBar.items` was fixed for and the same fix: the
 * package's own documented example is the honest value to start from, and it
 * stays fully editable in the panel afterwards.
 */
function documentedExample(
  propName: string,
  kind: PropSpecKind | undefined,
  rawValue: string | undefined,
  literal: string | undefined,
): unknown {
  if (kind === 'collection') return literal === undefined ? undefined : exampleFromLiteral(literal)
  return documentedScalarExample(propName, kind, rawValue)
}

function buildProps(name: string, catalog: DesignSystemCatalog): PropSpec[] {
  let propNames: string[] | null
  try {
    propNames = catalog.propsFor(name)
  } catch {
    propNames = null
  }

  let doc: string | null
  try {
    doc = catalog.apiDoc(name)
  } catch {
    doc = null
  }

  const enumValues = parseEnumValues(doc)
  const propValues = parsePropValues(doc)
  const propLiterals = parsePropLiterals(doc)

  const propComments = parsePropComments(doc)

  const specs = (propNames ?? []).map((propName): PropSpec => {
    const spec: PropSpec = {
      name: propName,
      tsType: 'unknown',
      required: false,
    }
    const values = enumValues.get(propName)
    if (values) {
      spec.enumValues = values
    }
    // An enum beats the value form: `bg="default" // default | primary | dim`
    // reads as a plain string by shape, and the comment is what says it is a
    // closed set. Everything else takes the form's answer.
    let kind = values ? 'enum' : classifyPropValue(propName, propValues.get(propName) ?? '')
    // A documented string that names an image is an image, not free text.
    if (kind === 'string' && isImageProp(propName)) kind = 'image'
    if (kind) spec.kind = kind
    const example = documentedExample(propName, kind, propValues.get(propName), propLiterals.get(propName))
    if (example !== undefined) spec.example = example
    return spec
  })

  return withCollectionIndexLinks(specs, propComments)
}

/**
 * Links a number prop the docs call an INDEX to the collection it indexes.
 *
 * `TabBar`'s `value={0}  // active tab index (0-based, controlled)` is the whole
 * of "which tab is currently selected", and the panel rendered it as a text
 * field labelled `value` holding `0` — an edit you could make and had no way to
 * understand. Naming the collection lets the panel offer the tabs themselves.
 *
 * Two conditions, both required, because a wrong link is worse than none: the
 * prop's own doc comment must call it an index, and the component must have
 * exactly ONE collection prop — with two, nothing in the docs says which one is
 * meant, and picking either would be a guess.
 */
function withCollectionIndexLinks(specs: PropSpec[], propComments: Map<string, string>): PropSpec[] {
  const collections = specs.filter((spec) => spec.kind === 'collection')
  if (collections.length !== 1) return specs
  const collection = collections[0]!.name
  for (const spec of specs) {
    if (spec.kind !== 'number') continue
    if (!/\bindex\b/i.test(propComments.get(spec.name) ?? '')) continue
    spec.indexesCollection = collection
  }
  return specs
}

/**
 * Fills in `enumValues` for a prop the docs describe only by where it GOES:
 * `buttonVariant="primary"  // forwarded to the inner Button`.
 *
 * The options for such a prop are documented once, on the component that
 * actually owns it, and the forwarding site gets a prose comment with no pipe
 * list — so the value-form pass reads a plain string and the panel renders a
 * text box you have to know the vocabulary to fill in. The NAME is the link:
 * `<component><Prop>` in camelCase, where `<component>` is a real component in
 * this same manifest and `<Prop>` is one of its documented enum props.
 *
 * Deliberately narrow. It fires only when the owning component exists, the
 * target prop exists on it, and that prop already has a documented enum —
 * three independent confirmations from the package's own docs, not an
 * inference about what a name might mean. A prop that matches the shape but
 * fails any of them keeps its text box.
 */
function inheritForwardedEnums(components: ComponentSpec[]): void {
  const byLowerName = new Map(components.map((component) => [component.name.toLowerCase(), component]))

  for (const component of components) {
    for (const prop of component.props) {
      if (prop.enumValues) continue
      const parts = /^([a-z]+)([A-Z]\w*)$/.exec(prop.name)
      if (!parts) continue
      const owner = byLowerName.get(parts[1]!)
      if (!owner || owner === component) continue
      const targetName = parts[2]!.charAt(0).toLowerCase() + parts[2]!.slice(1)
      const target = owner.props.find((candidate) => candidate.name === targetName)
      if (!target?.enumValues) continue
      prop.enumValues = [...target.enumValues]
      prop.kind = 'enum'
    }
  }
}

/**
 * Fills in `enumValues` from the package's own STYLESHEET, for a prop the docs
 * describe by the class it produces: `imageSize="small" // sizes the image
 * section (marketing-card--img-{size})`.
 *
 * That comment names the options exactly — they are whichever
 * `marketing-card--img-*` classes the shipped CSS defines — it just does not
 * list them. Reading them out of the stylesheet is a lookup in the package's
 * own build output, not a guess: a value with no rule behind it does nothing,
 * and a rule with no value is unreachable, so the class list IS the option
 * list.
 */
function inheritTemplatedClassEnums(components: ComponentSpec[], css: string, docFor: (name: string) => string | null): void {
  for (const component of components) {
    const doc = docFor(component.name)
    if (!doc) continue
    for (const prop of component.props) {
      if (prop.enumValues) continue
      // `imageSize="small" // … (marketing-card--img-{size})`
      const line = new RegExp(`^\\s*${prop.name}\\s*=.*\\(([a-z-]+--[a-z-]*)\\{\\w+\\}\\)`, 'm').exec(doc)
      if (!line) continue
      const prefix = line[1]!
      const found = new Set<string>()
      for (const match of css.matchAll(new RegExp(`\\.${prefix}([a-z0-9]+)(?![a-z0-9-])`, 'g'))) {
        found.add(match[1]!)
      }
      if (found.size < 2) continue
      prop.enumValues = [...found].sort()
      prop.kind = 'enum'
    }
  }
}

/** The package's shipped stylesheet, or `''` when it has none — a missing stylesheet costs the templated-class pass, nothing else. */
function readPackageCss(pkgRoot: string): string {
  try {
    return readFileSync(join(pkgRoot, 'dist/index.css'), 'utf8')
  } catch {
    return ''
  }
}

export async function buildDesignSystemManifest(): Promise<ComponentManifest> {
  const pkgRoot = resolvePackageRoot()
  const catalogUrl = pathToFileURL(join(pkgRoot, 'mcp/catalog.js')).href
  const catalog = (await import(catalogUrl)) as DesignSystemCatalog

  const components: ComponentSpec[] = catalog.componentNames.map((name) => ({
    name,
    file: FILE_SPECIFIER,
    exportName: name,
    isDefaultExport: false,
    props: buildProps(name, catalog),
  }))

  // Two recovery passes for props the docs describe without listing their
  // options. Both run AFTER every component is built, because both need to
  // read something outside the prop's own documentation line.
  inheritForwardedEnums(components)
  inheritTemplatedClassEnums(components, readPackageCss(pkgRoot), (name) => {
    try {
      return catalog.apiDoc(name)
    } catch {
      return null
    }
  })

  return { components }
}
