/**
 * Builds a `ComponentManifest` for `@alm-design/design-system` FROM the
 * package's own catalog module (`<pkgRoot>/mcp/catalog.js`) — not from local
 * files and not from `react-docgen`. The catalog is generated by the design
 * system itself from its source-of-truth docs (`CLAUDE.md` / `design.md` /
 * `src/index.js`), so it's the most reliable list of public components and
 * their real usage.
 *
 * NOTE on `ComponentSpec.file`: for package-sourced components there is no
 * local file to point at, so `file` holds the bare import specifier
 * (`'@alm-design/design-system'`) that a consumer would actually import
 * from — not a filesystem path.
 */
import { readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { pathToFileURL } from 'node:url'
import type { ComponentManifest, ComponentSpec, PropSpec, PropSpecKind } from '../component-manifest/types'

const PACKAGE_NAME = '@alm-design/design-system'
const FILE_SPECIFIER = PACKAGE_NAME

/** Shape of the subset of `mcp/catalog.js`'s exports we rely on. */
interface DesignSystemCatalog {
  componentNames: string[]
  propsFor(name: string): string[] | null
  apiDoc(name: string): string | null
}

/**
 * Matches a JSX usage-example line like:
 *   size="regular"         // regular | small
 * Group 1 is the prop name, group 2 is the raw comment text after `//`.
 * The lazy `.*?` before `//` means we don't try to parse the prop's value
 * (which may itself contain braces/slashes, e.g. `leadingIcon={<Icon />}`)
 * — we just need the first `//` after the `propName=` to locate the comment.
 */
const ENUM_COMMENT_LINE = /^([A-Za-z_$][A-Za-z0-9_$]*)=.*?\/\/\s*(.+)$/

/**
 * Best-effort extraction of enum values per prop from a component's API doc.
 * Parses the first fenced code block (the JSX usage example) line by line;
 * for any line matching `propName=... // a | b | c`, splits the comment on
 * `|` and keeps the trimmed, non-empty tokens if there are at least two.
 * Never throws — returns an empty map for anything it can't parse.
 */
function parseEnumValues(doc: string | null): Map<string, string[]> {
  const enums = new Map<string, string[]>()
  if (!doc) return enums

  const block = /```[a-z]*\n([\s\S]*?)```/i.exec(doc)
  if (!block) return enums

  for (const rawLine of block[1].split('\n')) {
    const line = rawLine.trim()
    const match = ENUM_COMMENT_LINE.exec(line)
    if (!match) continue

    const [, propName, commentText] = match
    const tokens = commentText
      .split('|')
      .map((token) => token.trim())
      .filter((token) => token.length > 0)
      // Reduce each token to just its value: the substring before the first
      // whitespace or `(`. Drops trailing prose/annotations (e.g. "default
      // (48px)" -> "default", "rtl — via useDir; ..." -> "rtl") while
      // leaving hyphenated values with no space/paren intact (e.g.
      // "primary-inverted", "gpay-pay-with").
      .map((token) => token.split(/[\s(]/)[0])
      .filter((token) => token.length > 0)

    // Drop duplicate tokens (can arise after cleaning, e.g. two prose
    // variants of the same base value) while preserving first-seen order.
    const uniqueTokens = [...new Set(tokens)]

    if (uniqueTokens.length >= 2) {
      enums.set(propName, uniqueTokens)
    }
  }

  return enums
}

/** Resolves the installed package's root directory. */
function resolvePackageRoot(): string {
  try {
    const require = createRequire(import.meta.url)
    return dirname(require.resolve(`${PACKAGE_NAME}/package.json`))
  } catch {
    return join(process.cwd(), 'node_modules', PACKAGE_NAME)
  }
}

/**
 * Matches a JSX usage-example line's prop NAME and raw VALUE:
 *   skeleton={false}       // renders a shimmer
 *   icon={<SvgIcon />}
 *   bg="default"           // default | primary | dim
 * Group 2 is everything after `=` up to a trailing `//` comment (which
 * `ENUM_COMMENT_LINE` above parses separately). Deliberately greedy up to the
 * comment so a braced value containing `/` (`<Icon a="b/c"/>`) survives.
 */
const PROP_VALUE_LINE = /^([A-Za-z_$][A-Za-z0-9_$]*)=(.*?)(?:\s*\/\/.*)?$/

/**
 * The prop kinds this package's docs can express, read off the VALUE FORM in
 * each component's JSX example. Nothing here guesses from the prop's NAME
 * except the icon/node distinction, which is a presentation choice (both are
 * React nodes; an icon-named one gets a picker instead of a bare slot).
 *
 * A form this does not recognise — a structured `{[…]}` array, a `{{…}}`
 * object, an interpolation — returns `undefined` rather than a wrong answer,
 * and the prop keeps whatever the enum pass gave it (or falls through to
 * `'unknown'`, i.e. a text box). That is the honest failure mode: a text box
 * for a value we could not classify, never a toggle for something that is not
 * a boolean.
 */
function classifyPropValue(propName: string, rawValue: string): PropSpecKind | undefined {
  const value = rawValue.trim()
  if (value === '') return undefined

  // `prop` with no `=` in JSX means `prop={true}`; the docs write it out.
  if (/^\{(true|false)\}$/.test(value)) return 'boolean'
  if (/^\{-?\d+(\.\d+)?\}$/.test(value)) return 'number'
  // `{fn}`, `{() => …}`, `{handleX}` — a callback. Never editable: a text box
  // here can only write a string where the component expects a function.
  if (/^\{(fn|\(\)\s*=>|\w*[Hh]andler\b|on[A-Z])/.test(value) || /^on[A-Z]/.test(propName)) return 'handler'
  if (/^\{\s*</.test(value)) return ICON_PROP_NAME_RE.test(propName) ? 'icon' : 'node'
  if (/^["']/.test(value)) return 'string'
  return undefined
}

/** A prop whose node value is an ICON rather than arbitrary content — it gets the icon picker instead of a generic slot row. */
const ICON_PROP_NAME_RE = /(^|[a-z])icon([A-Z0-9]|$)/i

/**
 * A string prop naming an IMAGE the user supplies: `imageSrc`,
 * `partnerLogoSrc`, `cardArt`, `avatarUrl`.
 *
 * These are documented as plain strings (`imageSrc="/transfer.jpg"`), so the
 * value-form pass classifies them `'string'` and the panel renders a text box
 * — asking a designer to type a path to a file they have not uploaded
 * anywhere. The image control has an upload affordance AND still accepts a
 * URL, so it is a strict superset of what the text box could do.
 *
 * Matched on the name because that is the only signal the docs carry: a URL
 * and a label are the same shape. The image word must END the name — an
 * earlier version matched it anywhere and classified `imageActionLabel` (a
 * LABEL) as an image. `iconSrc` is deliberately excluded: an icon prop
 * already has its own richer picker.
 */
const IMAGE_PROP_NAME_RE = /(src|image|logo|photo|avatar|thumbnail|poster|banner|art)$/i

/** Whether `propName` names an image source — see {@link IMAGE_PROP_NAME_RE}. */
function isImageProp(propName: string): boolean {
  if (ICON_PROP_NAME_RE.test(propName)) return false
  return IMAGE_PROP_NAME_RE.test(propName)
}

/** Prop name -> raw documented value, from the first fenced JSX block. Same block `parseEnumValues` reads. */
function parsePropValues(doc: string | null): Map<string, string> {
  const values = new Map<string, string>()
  if (!doc) return values
  const block = /```[a-z]*\n([\s\S]*?)```/i.exec(doc)
  if (!block) return values
  for (const rawLine of block[1].split('\n')) {
    const match = PROP_VALUE_LINE.exec(rawLine.trim())
    if (!match) continue
    const [, propName, rawValue] = match
    if (!values.has(propName)) values.set(propName, rawValue)
  }
  return values
}

function buildProps(name: string, catalog: DesignSystemCatalog): PropSpec[] {
  let propNames: string[] | null
  try {
    propNames = catalog.propsFor(name)
  } catch {
    propNames = null
  }

  let doc: string | null
  try {
    doc = catalog.apiDoc(name)
  } catch {
    doc = null
  }

  const enumValues = parseEnumValues(doc)
  const propValues = parsePropValues(doc)

  return (propNames ?? []).map((propName): PropSpec => {
    const spec: PropSpec = {
      name: propName,
      tsType: 'unknown',
      required: false,
    }
    const values = enumValues.get(propName)
    if (values) {
      spec.enumValues = values
    }
    // An enum beats the value form: `bg="default" // default | primary | dim`
    // reads as a plain string by shape, and the comment is what says it is a
    // closed set. Everything else takes the form's answer.
    let kind = values ? 'enum' : classifyPropValue(propName, propValues.get(propName) ?? '')
    // A documented string that names an image is an image, not free text.
    if (kind === 'string' && isImageProp(propName)) kind = 'image'
    if (kind) spec.kind = kind
    return spec
  })
}

/**
 * Fills in `enumValues` for a prop the docs describe only by where it GOES:
 * `buttonVariant="primary"  // forwarded to the inner Button`.
 *
 * The options for such a prop are documented once, on the component that
 * actually owns it, and the forwarding site gets a prose comment with no pipe
 * list — so the value-form pass reads a plain string and the panel renders a
 * text box you have to know the vocabulary to fill in. The NAME is the link:
 * `<component><Prop>` in camelCase, where `<component>` is a real component in
 * this same manifest and `<Prop>` is one of its documented enum props.
 *
 * Deliberately narrow. It fires only when the owning component exists, the
 * target prop exists on it, and that prop already has a documented enum —
 * three independent confirmations from the package's own docs, not an
 * inference about what a name might mean. A prop that matches the shape but
 * fails any of them keeps its text box.
 */
function inheritForwardedEnums(components: ComponentSpec[]): void {
  const byLowerName = new Map(components.map((component) => [component.name.toLowerCase(), component]))

  for (const component of components) {
    for (const prop of component.props) {
      if (prop.enumValues) continue
      const parts = /^([a-z]+)([A-Z]\w*)$/.exec(prop.name)
      if (!parts) continue
      const owner = byLowerName.get(parts[1]!)
      if (!owner || owner === component) continue
      const targetName = parts[2]!.charAt(0).toLowerCase() + parts[2]!.slice(1)
      const target = owner.props.find((candidate) => candidate.name === targetName)
      if (!target?.enumValues) continue
      prop.enumValues = [...target.enumValues]
      prop.kind = 'enum'
    }
  }
}

/**
 * Fills in `enumValues` from the package's own STYLESHEET, for a prop the docs
 * describe by the class it produces: `imageSize="small" // sizes the image
 * section (marketing-card--img-{size})`.
 *
 * That comment names the options exactly — they are whichever
 * `marketing-card--img-*` classes the shipped CSS defines — it just does not
 * list them. Reading them out of the stylesheet is a lookup in the package's
 * own build output, not a guess: a value with no rule behind it does nothing,
 * and a rule with no value is unreachable, so the class list IS the option
 * list.
 */
function inheritTemplatedClassEnums(components: ComponentSpec[], css: string, docFor: (name: string) => string | null): void {
  for (const component of components) {
    const doc = docFor(component.name)
    if (!doc) continue
    for (const prop of component.props) {
      if (prop.enumValues) continue
      // `imageSize="small" // … (marketing-card--img-{size})`
      const line = new RegExp(`^\\s*${prop.name}\\s*=.*\\(([a-z-]+--[a-z-]*)\\{\\w+\\}\\)`, 'm').exec(doc)
      if (!line) continue
      const prefix = line[1]!
      const found = new Set<string>()
      for (const match of css.matchAll(new RegExp(`\\.${prefix}([a-z0-9]+)(?![a-z0-9-])`, 'g'))) {
        found.add(match[1]!)
      }
      if (found.size < 2) continue
      prop.enumValues = [...found].sort()
      prop.kind = 'enum'
    }
  }
}

/** The package's shipped stylesheet, or `''` when it has none — a missing stylesheet costs the templated-class pass, nothing else. */
function readPackageCss(pkgRoot: string): string {
  try {
    return readFileSync(join(pkgRoot, 'dist/index.css'), 'utf8')
  } catch {
    return ''
  }
}

export async function buildDesignSystemManifest(): Promise<ComponentManifest> {
  const pkgRoot = resolvePackageRoot()
  const catalogUrl = pathToFileURL(join(pkgRoot, 'mcp/catalog.js')).href
  const catalog = (await import(catalogUrl)) as DesignSystemCatalog

  const components: ComponentSpec[] = catalog.componentNames.map((name) => ({
    name,
    file: FILE_SPECIFIER,
    exportName: name,
    isDefaultExport: false,
    props: buildProps(name, catalog),
  }))

  // Two recovery passes for props the docs describe without listing their
  // options. Both run AFTER every component is built, because both need to
  // read something outside the prop's own documentation line.
  inheritForwardedEnums(components)
  inheritTemplatedClassEnums(components, readPackageCss(pkgRoot), (name) => {
    try {
      return catalog.apiDoc(name)
    } catch {
      return null
    }
  })

  return { components }
}
