/**
 * TypeBox schemas for the three JSON boundaries around the vendored design
 * system.
 *
 * Two of them are hand-edited files inside the vendored package
 * (`studio/keywords.json`, `studio/groups.json`) — a typo there would
 * otherwise turn into a silently-empty keyword list. The third
 * (`dist/tokens.generated.json`) is generated by `bun run alm:sync` and read
 * back by the editor, so it is a genuine untyped boundary on the way in.
 *
 * Schemas are the source of truth: every type here is `Static<typeof …>`.
 */
import { Type, type Static } from '@core/utils/typeboxHelpers'

/**
 * One colour token from `src/tokens/*.css`, as recorded in
 * `dist/tokens.generated.json`.
 *
 * `light` and `dark` are always RENDERABLE CSS colour values: a semantic token
 * is declared as `var(--color-light)`, which no swatch can paint, so the
 * extraction resolves `var()` chains within the token set before recording
 * them. A raw token the dark theme does not redeclare keeps its light value in
 * `dark`, which is exactly what the cascade does.
 */
export const DesignSystemColorTokenSchema = Type.Object({
  /** The custom property name, including the leading `--`. */
  name: Type.String(),
  light: Type.String(),
  dark: Type.String(),
  /** Palette family or semantic family — see `extractColorTokens.ts`. */
  group: Type.String(),
})

export type DesignSystemColorToken = Static<typeof DesignSystemColorTokenSchema>

/** The whole of `dist/tokens.generated.json`. */
export const DesignSystemColorTokensSchema = Type.Array(DesignSystemColorTokenSchema)

/** `studio/keywords.json` — `{ "<ComponentName>": ["synonym", …] }`. */
export const DesignSystemKeywordsFileSchema = Type.Record(
  Type.String(),
  Type.Array(Type.String()),
)

export type DesignSystemKeywordsFile = Static<typeof DesignSystemKeywordsFileSchema>

/** `studio/groups.json` — `{ "<Group>": ["ComponentName", …] }`. */
export const DesignSystemGroupsFileSchema = Type.Record(
  Type.String(),
  Type.Array(Type.String()),
)

export type DesignSystemGroupsFile = Static<typeof DesignSystemGroupsFileSchema>
