export {
  TextAlignLeftIcon,
  TextAlignCenterIcon,
  TextAlignRightIcon,
  TextAlignJustifyIcon,
  TextItalicIcon,
  TextStrikethroughIcon,
  NoneSlashIcon,
  LineHeightIcon,
  LetterSpacingIcon,
  FlowRowIcon,
  FlowRowReverseIcon,
  FlowColumnIcon,
  FlowColumnReverseIcon,
  DisplayBlockIcon,
  DisplayFlexIcon,
  DisplayGridIcon,
  MinWidthIcon,
  MaxWidthIcon,
  MinHeightIcon,
  MaxHeightIcon,
  AspectRatioIcon,
  OpacityIcon,
  GapIcon,
  StrokeWeightIcon,
  CornerRadiusIcon,
  CommentBubbleIcon,
} from './InspectorIcons'
