/**
 * i18nScaffold — writes the two-file i18n module a project needs before it can
 * hold Arabic at all.
 *
 * The Content panel's read-only state ("no locale dictionary in this project")
 * is honest but terminal: every string is mapped and none can be translated,
 * because there is nowhere in the user's repo to put the Arabic. This is the
 * way out, and it is deliberately a REAL module in the user's source — not a
 * Studio sidecar — because Studio's premise is that the repository is the
 * document. A translation that only exists in Studio is a translation their app
 * never ships.
 *
 * ## Why this exact shape
 *
 * The generated code is not a style preference; every line of it is load-bearing
 * for Studio's static evaluator, which resolves what the canvas shows WITHOUT
 * executing a single line (`docs/features/studio-import.md`, §7). Three
 * constraints fix the shape:
 *
 * 1. **`localeProbe.ts` rule 1 must detect it.** That needs a top-level object
 *    literal (`export const translations = {`) whose own keys are locale codes,
 *    plus an `translations[<identifier>]` element access somewhere in the
 *    project. `LanguageContext.tsx` supplies the access.
 * 2. **`staticEvalCalls.ts` Tier B must trace it.** The hook reads
 *    `useContext(...)` as its first statement, and exactly one
 *    `<LanguageContext.Provider value={…}>` exists in the workspace — both
 *    required by `tryProviderTraceCached`/`traceProvider`. The provider's value
 *    is the `useMemo` object holding `t: translations[lang]`, and the canvas
 *    picks the `lang` BRANCH by preview locale (§7.4), which is what makes the
 *    RTL/Arabic board show Arabic.
 * 3. **The hook must work with no provider mounted.** `createContext` is given
 *    a real default carrying the English dictionary, so a component that calls
 *    `useLanguage()` before the user has wrapped their app renders English
 *    rather than crashing. An extraction can therefore never break a running
 *    app — the worst case is untranslated copy, which is exactly what was there
 *    before.
 *
 * Point 3 is why this does not copy the project corpus's usual
 * `if (!ctx) throw new Error(...)` guard: that guard turns "Studio extracted a
 * string" into a white screen for anyone who has not also wired the provider.
 *
 * ## What it refuses
 *
 * A project that already has a dictionary. `detectLocales` returning non-null
 * means there is somewhere real to write, and a second mechanism beside the
 * first is exactly the "two ways to do one thing" the repo bans. To EXTRACT
 * into a dictionary that already exists, see {@link findScaffoldedI18n} —
 * scaffolding and extracting are separate steps for exactly this reason.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { dirname as posixDirname, join as posixJoin } from 'node:path/posix'
import { resolveAppRoot } from './appRoot'
import { detectLocales } from './localeProbe'
import type { TranslationCatalog } from './translationCatalog'

/** The locales every Studio-scaffolded project starts with. English is the source copy; Arabic is what the AI action fills. */
export const SCAFFOLD_LOCALES = ['en', 'ar'] as const

/** Named export the extraction codemod imports and calls. */
export const SCAFFOLD_HOOK_NAME = 'useLanguage'

export interface I18nScaffold {
  /** App-root-relative POSIX path of the dictionary module. */
  translationsRel: string
  /** App-root-relative POSIX path of the context module — where {@link SCAFFOLD_HOOK_NAME} lives. */
  contextRel: string
  /** Absolute path of the directory both live in. */
  dirAbs: string
}

export type ScaffoldResult = { ok: true; scaffold: I18nScaffold } | { ok: false; message: string }

function translationsModule(): string {
  return `/**
 * translations — every user-facing string in this app, in every language it
 * ships. Studio's Content panel reads and writes this file directly.
 *
 * Add a key to BOTH locales. A key missing from \`ar\` falls back to nothing,
 * not to English, so an untranslated string shows as blank in Arabic.
 */
export const translations = {
  en: {},
  ar: {},
}

/** The locale codes this app declares. */
export type Locale = keyof typeof translations

/** The language used when nothing else has been chosen. */
export const defaultLocale: Locale = 'en'
`
}

function contextModule(): string {
  return `import { createContext, useContext, useMemo, useState, type ReactNode } from 'react'
import { translations, defaultLocale, type Locale } from './translations'

/**
 * LanguageContext — the current language, the strings for it, and the way to
 * switch. Generated by Studio.
 *
 * The default value carries the English dictionary on purpose: \`useLanguage()\`
 * works with no <LanguageProvider> mounted, so adding a translated string to a
 * component can never break a screen. Wrap your app in <LanguageProvider> when
 * you want language switching and RTL to actually take effect.
 */
const LanguageContext = createContext({
  lang: defaultLocale,
  dir: 'ltr' as 'ltr' | 'rtl',
  t: translations[defaultLocale],
  setLang: (_lang: Locale) => {},
})

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Locale>(defaultLocale)

  const value = useMemo(
    () => ({
      lang,
      dir: lang === 'ar' ? ('rtl' as const) : ('ltr' as const),
      t: translations[lang],
      setLang,
    }),
    [lang],
  )

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

/** \`const { t } = useLanguage()\` — the strings for the active language. */
export function useLanguage() {
  const ctx = useContext(LanguageContext)
  return ctx
}
`
}

/**
 * Where a NEW i18n module goes: beside the rest of the source when the
 * project has a `src/`, at the app root otherwise. Both are conventional;
 * guessing deeper (next to the pages directory, inside a `lib/`) would be a
 * guess about a layout this function cannot see.
 *
 * This heuristic is only ever a good answer to "where should Studio create
 * one" — a project with NO dictionary yet has no fact to consult, so a
 * convention is the honest best a create path can do. It must never be
 * reused to answer "where is the dictionary that already exists": that
 * project already carries the real answer (`localeProbe.ts`'s detected
 * `LocalesCapability.source`), and re-guessing at find-time silently
 * overrides a known fact with a coin flip — see {@link findScaffoldedI18n}.
 */
function defaultScaffoldDir(appRootAbs: string): { abs: string; rel: string } {
  const hasSrc = existsSync(join(appRootAbs, 'src'))
  const rel = hasSrc ? 'src/i18n' : 'i18n'
  return { abs: join(appRootAbs, ...rel.split('/')), rel }
}

/**
 * Creates `<src>/i18n/{translations.ts,LanguageContext.tsx}`, or reports why
 * it did not. Never throws.
 *
 * Callers must re-probe the project profile afterwards — `localeProbe` only
 * sees these files on the next probe, and `resolveProjectProfile` serves a
 * cached profile until something invalidates it.
 */
export function scaffoldProjectI18n(dir: string): ScaffoldResult {
  try {
    const appRootAbs = resolveAppRoot(dir)
    if (detectLocales(appRootAbs)) {
      return { ok: false, message: 'This project already has a locale dictionary.' }
    }

    const { abs, rel } = defaultScaffoldDir(appRootAbs)
    const translationsAbs = join(abs, 'translations.ts')
    const contextAbs = join(abs, 'LanguageContext.tsx')
    if (existsSync(translationsAbs) || existsSync(contextAbs)) {
      return { ok: false, message: `${rel}/ already exists but Studio could not read a dictionary from it.` }
    }

    mkdirSync(abs, { recursive: true })
    writeFileSync(translationsAbs, translationsModule(), 'utf8')
    writeFileSync(contextAbs, contextModule(), 'utf8')

    return {
      ok: true,
      scaffold: { translationsRel: `${rel}/translations.ts`, contextRel: `${rel}/LanguageContext.tsx`, dirAbs: abs },
    }
  } catch (err) {
    console.error('[studio:i18nScaffold]', err)
    return { ok: false, message: err instanceof Error ? err.message : String(err) }
  }
}

/**
 * The Studio-written i18n module in a project that already has one, or
 * `undefined`.
 *
 * Extraction needs two things the dictionary itself does not carry: which
 * module exports the hook, and what the hook is called. For a Studio scaffold
 * both are known. For a project whose i18n it did not write — a hand-rolled
 * `LanguageContext`, an i18next setup, a `locales/` folder read through some
 * other hook — they are not, and guessing would mean writing an import to a
 * symbol that may not exist. So this recognises ONLY Studio's own shape, and
 * a project with a different one is refused with a reason rather than
 * half-rewritten.
 *
 * ## Find beside the dictionary that was actually found — never re-guess a directory
 *
 * This takes the ALREADY-RESOLVED {@link TranslationCatalog} (from
 * `readTranslationCatalog`, which in turn trusts `localeProbe.ts`'s detected
 * `LocalesCapability.source`) rather than re-deriving a directory from a
 * `src/`-exists heuristic. That heuristic is the right tool in
 * {@link scaffoldProjectI18n} — there is no dictionary yet, so a convention is
 * the only thing to consult — but it is the wrong tool here: the dictionary's
 * real location is a known fact once `readTranslationCatalog` has found it,
 * and a guess has no business overriding a known location (a project with a
 * `src/` directory whose Studio scaffold happens to live at the app root,
 * for example, would be refused with a false "not one Studio wrote" for no
 * reason but the guess landing on the wrong folder).
 *
 * A `locales/*.json` per-locale-file catalogue is never a Studio scaffold —
 * Studio's own shape is always the two-file `translations.ts` +
 * `LanguageContext.tsx` module — so that shape is rejected up front rather
 * than probed.
 *
 * Recognition is by content, not just by path: the context module beside the
 * dictionary must actually export {@link SCAFFOLD_HOOK_NAME}. This stays
 * strict on purpose — the extraction codemod writes a real `import { useLanguage }`
 * statement, so it must know the hook's exact exported name rather than infer
 * one. A Studio scaffold whose hook was hand-renamed after the fact is a
 * project that changed the contract, not one this function should guess back
 * into shape.
 */
export function findScaffoldedI18n(catalog: TranslationCatalog): I18nScaffold | undefined {
  try {
    // Studio's scaffold is a single dictionary module, never a `locales/`
    // directory of per-locale JSON files.
    if (catalog.perLocaleFiles) return undefined

    const dirAbs = dirname(catalog.sourceAbs)
    const contextAbs = join(dirAbs, 'LanguageContext.tsx')
    if (!existsSync(contextAbs)) return undefined
    if (!readFileSync(contextAbs, 'utf8').includes(`export function ${SCAFFOLD_HOOK_NAME}`)) return undefined

    const translationsRel = catalog.capability.source
    const contextRel = posixJoin(posixDirname(translationsRel), 'LanguageContext.tsx')
    return { translationsRel, contextRel, dirAbs }
  } catch (err) {
    console.error('[studio:i18nScaffold]', err)
    return undefined
  }
}
