/**
 * i18nScaffold — writes the two-file i18n module a project needs before it can
 * hold Arabic at all.
 *
 * The Content panel's read-only state ("no locale dictionary in this project")
 * is honest but terminal: every string is mapped and none can be translated,
 * because there is nowhere in the user's repo to put the Arabic. This is the
 * way out, and it is deliberately a REAL module in the user's source — not a
 * Studio sidecar — because Studio's premise is that the repository is the
 * document. A translation that only exists in Studio is a translation their app
 * never ships.
 *
 * ## Why this exact shape
 *
 * The generated code is not a style preference; every line of it is load-bearing
 * for Studio's static evaluator, which resolves what the canvas shows WITHOUT
 * executing a single line (`docs/features/studio-import.md`, §7). Three
 * constraints fix the shape:
 *
 * 1. **`localeProbe.ts` rule 1 must detect it.** That needs a top-level object
 *    literal (`export const translations = {`) whose own keys are locale codes,
 *    plus an `translations[<identifier>]` element access somewhere in the
 *    project. `LanguageContext.tsx` supplies the access.
 * 2. **`staticEvalCalls.ts` Tier B must trace it.** The hook reads
 *    `useContext(...)` as its first statement, and exactly one
 *    `<LanguageContext.Provider value={…}>` exists in the workspace — both
 *    required by `tryProviderTraceCached`/`traceProvider`. The provider's value
 *    is the `useMemo` object holding `t: translations[lang]`, and the canvas
 *    picks the `lang` BRANCH by preview locale (§7.4), which is what makes the
 *    RTL/Arabic board show Arabic.
 * 3. **The hook must work with no provider mounted.** `createContext` is given
 *    a real default carrying the English dictionary, so a component that calls
 *    `useLanguage()` before the user has wrapped their app renders English
 *    rather than crashing. An extraction can therefore never break a running
 *    app — the worst case is untranslated copy, which is exactly what was there
 *    before.
 *
 * Point 3 is why this does not copy the project corpus's usual
 * `if (!ctx) throw new Error(...)` guard: that guard turns "Studio extracted a
 * string" into a white screen for anyone who has not also wired the provider.
 *
 * ## What it refuses
 *
 * A project that already has a dictionary. `detectLocales` returning non-null
 * means there is somewhere real to write, and a second mechanism beside the
 * first is exactly the "two ways to do one thing" the repo bans. To EXTRACT
 * into a dictionary that already exists, see {@link findScaffoldedI18n} —
 * scaffolding and extracting are separate steps for exactly this reason.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { resolveAppRoot } from './appRoot'
import { detectLocales } from './localeProbe'

/** The locales every Studio-scaffolded project starts with. English is the source copy; Arabic is what the AI action fills. */
export const SCAFFOLD_LOCALES = ['en', 'ar'] as const

/** Named export the extraction codemod imports and calls. */
export const SCAFFOLD_HOOK_NAME = 'useLanguage'

export interface I18nScaffold {
  /** App-root-relative POSIX path of the dictionary module. */
  translationsRel: string
  /** App-root-relative POSIX path of the context module — where {@link SCAFFOLD_HOOK_NAME} lives. */
  contextRel: string
  /** Absolute path of the directory both live in. */
  dirAbs: string
}

export type ScaffoldResult = { ok: true; scaffold: I18nScaffold } | { ok: false; message: string }

function translationsModule(): string {
  return `/**
 * translations — every user-facing string in this app, in every language it
 * ships. Studio's Content panel reads and writes this file directly.
 *
 * Add a key to BOTH locales. A key missing from \`ar\` falls back to nothing,
 * not to English, so an untranslated string shows as blank in Arabic.
 */
export const translations = {
  en: {},
  ar: {},
}

/** The locale codes this app declares. */
export type Locale = keyof typeof translations

/** The language used when nothing else has been chosen. */
export const defaultLocale: Locale = 'en'
`
}

function contextModule(): string {
  return `import { createContext, useContext, useMemo, useState, type ReactNode } from 'react'
import { translations, defaultLocale, type Locale } from './translations'

/**
 * LanguageContext — the current language, the strings for it, and the way to
 * switch. Generated by Studio.
 *
 * The default value carries the English dictionary on purpose: \`useLanguage()\`
 * works with no <LanguageProvider> mounted, so adding a translated string to a
 * component can never break a screen. Wrap your app in <LanguageProvider> when
 * you want language switching and RTL to actually take effect.
 */
const LanguageContext = createContext({
  lang: defaultLocale,
  dir: 'ltr' as 'ltr' | 'rtl',
  t: translations[defaultLocale],
  setLang: (_lang: Locale) => {},
})

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Locale>(defaultLocale)

  const value = useMemo(
    () => ({
      lang,
      dir: lang === 'ar' ? ('rtl' as const) : ('ltr' as const),
      t: translations[lang],
      setLang,
    }),
    [lang],
  )

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

/** \`const { t } = useLanguage()\` — the strings for the active language. */
export function useLanguage() {
  const ctx = useContext(LanguageContext)
  return ctx
}
`
}

/**
 * Where the i18n module goes: beside the rest of the source when the project
 * has a `src/`, at the app root otherwise. Both are conventional; guessing
 * deeper (next to the pages directory, inside a `lib/`) would be a guess about
 * a layout this function cannot see.
 */
function scaffoldDir(appRootAbs: string): { abs: string; rel: string } {
  const hasSrc = existsSync(join(appRootAbs, 'src'))
  const rel = hasSrc ? 'src/i18n' : 'i18n'
  return { abs: join(appRootAbs, ...rel.split('/')), rel }
}

/**
 * Creates `<src>/i18n/{translations.ts,LanguageContext.tsx}`, or reports why
 * it did not. Never throws.
 *
 * Callers must re-probe the project profile afterwards — `localeProbe` only
 * sees these files on the next probe, and `resolveProjectProfile` serves a
 * cached profile until something invalidates it.
 */
export function scaffoldProjectI18n(dir: string): ScaffoldResult {
  try {
    const appRootAbs = resolveAppRoot(dir)
    if (detectLocales(appRootAbs)) {
      return { ok: false, message: 'This project already has a locale dictionary.' }
    }

    const { abs, rel } = scaffoldDir(appRootAbs)
    const translationsAbs = join(abs, 'translations.ts')
    const contextAbs = join(abs, 'LanguageContext.tsx')
    if (existsSync(translationsAbs) || existsSync(contextAbs)) {
      return { ok: false, message: `${rel}/ already exists but Studio could not read a dictionary from it.` }
    }

    mkdirSync(abs, { recursive: true })
    writeFileSync(translationsAbs, translationsModule(), 'utf8')
    writeFileSync(contextAbs, contextModule(), 'utf8')

    return {
      ok: true,
      scaffold: { translationsRel: `${rel}/translations.ts`, contextRel: `${rel}/LanguageContext.tsx`, dirAbs: abs },
    }
  } catch (err) {
    console.error('[studio:i18nScaffold]', err)
    return { ok: false, message: err instanceof Error ? err.message : String(err) }
  }
}

/**
 * The Studio-written i18n module in a project that already has one, or
 * `undefined`.
 *
 * Extraction needs two things the dictionary itself does not carry: which
 * module exports the hook, and what the hook is called. For a Studio scaffold
 * both are known. For a project whose i18n it did not write — a hand-rolled
 * `LanguageContext`, an i18next setup, a `locales/` folder read through some
 * other hook — they are not, and guessing would mean writing an import to a
 * symbol that may not exist. So this recognises ONLY Studio's own shape, and
 * a project with a different one is refused with a reason rather than
 * half-rewritten.
 *
 * Recognition is by content, not just by path: the context module must
 * actually export {@link SCAFFOLD_HOOK_NAME}.
 */
export function findScaffoldedI18n(dir: string): I18nScaffold | undefined {
  try {
    const appRootAbs = resolveAppRoot(dir)
    const { abs, rel } = scaffoldDir(appRootAbs)
    const contextAbs = join(abs, 'LanguageContext.tsx')
    const translationsAbs = join(abs, 'translations.ts')
    if (!existsSync(contextAbs) || !existsSync(translationsAbs)) return undefined
    if (!readFileSync(contextAbs, 'utf8').includes(`export function ${SCAFFOLD_HOOK_NAME}`)) return undefined
    return { translationsRel: `${rel}/translations.ts`, contextRel: `${rel}/LanguageContext.tsx`, dirAbs: abs }
  } catch (err) {
    console.error('[studio:i18nScaffold]', err)
    return undefined
  }
}
