import type { TreeNode } from '@ccs/protocol';

/**
 * TEST-ONLY `tree-snapshot` fixtures (P5 RESUME item 2 — the daemon gap
 * this doc used to describe is closed: `packages/sync-daemon`'s
 * `tree-snapshot.ts` now emits the real, frozen `tree-snapshot`
 * `DaemonEvent`, and `workspace-store.ts`'s `trees` map is populated from
 * it via `use-tree-snapshot-sync.ts`, not from this file). Production code
 * (`LayersPanel`/`Inspector`/`workspace-store`) no longer imports
 * `MOCK_FRAME_TREES` — ONLY `*.test.ts` files seed `workspace-store`'s
 * `trees` directly via `setTreeSnapshot(framePath, fixtureTree)` when they
 * need a tree without a real daemon connection. Kept around (uid format
 * matching the ADR-0017 `d<root>.<idx>...` astPath encoding) purely as
 * convenient, hand-authored unit-test data — `findNodeByUid` below is
 * still used by the real store's `selectedNode()`.
 *
 * `heroTree` mirrors `files/demo/src/frames/Hero.tsx` byte-for-byte
 * (section > h1, p, button, button — all static, editable). `pricingTree`
 * mirrors `files/demo/src/frames/Pricing.tsx` (the repo's real Arabic/RTL
 * fixture frame). `testimonialsTree` is synthetic: it demonstrates a
 * `.map()`-generated list (`dynamic: true` throughout the mapped subtree,
 * playbook §0 editable-surface contract) for tests that need a dynamic
 * node without depending on a real daemon/file fixture.
 */

const HERO_PATH = 'src/frames/Hero.tsx';
const PRICING_PATH = 'src/frames/Pricing.tsx';
const TESTIMONIALS_PATH = 'src/frames/Testimonials.tsx';

export const heroTree: TreeNode = {
  uid: `${HERO_PATH}:d0`,
  kind: 'element',
  tag: 'section',
  dynamic: false,
  children: [
    { uid: `${HERO_PATH}:d0.0`, kind: 'element', tag: 'h1', dynamic: false, children: [] },
    { uid: `${HERO_PATH}:d0.1`, kind: 'element', tag: 'p', dynamic: false, children: [] },
    { uid: `${HERO_PATH}:d0.2`, kind: 'element', tag: 'button', dynamic: false, children: [] },
    { uid: `${HERO_PATH}:d0.3`, kind: 'element', tag: 'button', dynamic: false, children: [] },
  ],
};

export const pricingTree: TreeNode = {
  uid: `${PRICING_PATH}:d0`,
  kind: 'element',
  tag: 'section',
  dynamic: false,
  children: [
    { uid: `${PRICING_PATH}:d0.0`, kind: 'element', tag: 'h1', dynamic: false, children: [] },
    { uid: `${PRICING_PATH}:d0.1`, kind: 'element', tag: 'p', dynamic: false, children: [] },
    {
      uid: `${PRICING_PATH}:d0.2`,
      kind: 'element',
      tag: 'div',
      dynamic: false,
      children: [
        { uid: `${PRICING_PATH}:d0.2.0`, kind: 'element', tag: 'span', dynamic: false, children: [] },
        { uid: `${PRICING_PATH}:d0.2.1`, kind: 'element', tag: 'span', dynamic: false, children: [] },
        { uid: `${PRICING_PATH}:d0.2.2`, kind: 'element', tag: 'button', dynamic: false, children: [] },
      ],
    },
  ],
};

export const testimonialsTree: TreeNode = {
  uid: `${TESTIMONIALS_PATH}:d0`,
  kind: 'element',
  tag: 'section',
  dynamic: false,
  children: [
    { uid: `${TESTIMONIALS_PATH}:d0.0`, kind: 'element', tag: 'h2', dynamic: false, children: [] },
    {
      uid: `${TESTIMONIALS_PATH}:d0.1`,
      kind: 'element',
      tag: 'div',
      dynamic: false,
      children: [
        // Everything below this point is generated by `.map()` in the
        // source — locked per the editable-surface contract (playbook §0).
        {
          uid: `${TESTIMONIALS_PATH}:d0.1.0`,
          kind: 'component-instance',
          tag: 'TestimonialCard',
          dynamic: true,
          component: 'ds:Card',
          children: [
            { uid: `${TESTIMONIALS_PATH}:d0.1.0.0`, kind: 'text', tag: null, dynamic: true, children: [] },
          ],
        },
        {
          uid: `${TESTIMONIALS_PATH}:d0.1.1`,
          kind: 'component-instance',
          tag: 'TestimonialCard',
          dynamic: true,
          component: 'ds:Card',
          children: [
            { uid: `${TESTIMONIALS_PATH}:d0.1.1.0`, kind: 'text', tag: null, dynamic: true, children: [] },
          ],
        },
      ],
    },
  ],
};

export interface FrameTreeFixture {
  frameName: string;
  framePath: string;
  tree: TreeNode;
}

export const MOCK_FRAME_TREES: FrameTreeFixture[] = [
  { frameName: 'Hero', framePath: HERO_PATH, tree: heroTree },
  { frameName: 'Pricing', framePath: PRICING_PATH, tree: pricingTree },
  { frameName: 'Testimonials', framePath: TESTIMONIALS_PATH, tree: testimonialsTree },
];

export function findNodeByUid(tree: TreeNode, uid: string): TreeNode | null {
  if (tree.uid === uid) return tree;
  for (const child of tree.children) {
    const found = findNodeByUid(child, uid);
    if (found) return found;
  }
  return null;
}
