// AUTO-GENERATED by @ccs/tokens — do not hand-edit.
// Source: design-system/src/tokens/tokens.js — regenerated by the
// sync-daemon's design-system watch (playbook §4/P4).
export default {
  "theme": {
    "extend": {
      "colors": {
        "metal": "var(--color-metal)",
        "chateau": "var(--color-chateau)",
        "montreal": "var(--color-montreal)",
        "gainsboro": "var(--color-gainsboro)",
        "alice": "var(--color-alice)",
        "ghost": "var(--color-ghost)",
        "light": "var(--color-light)",
        "white-static": "var(--color-white-static)",
        "metal-static": "var(--color-metal-static)",
        "aqua-10": "var(--color-aqua-10)",
        "aqua-30": "var(--color-aqua-30)",
        "aqua-50": "var(--color-aqua-50)",
        "aqua-100": "var(--color-aqua-100)",
        "aqua-200": "var(--color-aqua-200)",
        "coral-10": "var(--color-coral-10)",
        "coral-100": "var(--color-coral-100)",
        "coral-200": "var(--color-coral-200)",
        "forest-10": "var(--color-forest-10)",
        "forest-100": "var(--color-forest-100)",
        "forest-200": "var(--color-forest-200)",
        "butter-10": "var(--color-butter-10)",
        "butter-100": "var(--color-butter-100)",
        "lavender": "var(--color-lavender)",
        "iris": "var(--color-iris)",
        "almosafer": "var(--color-almosafer)",
        "whatsapp": "var(--color-whatsapp)",
        "facebook": "var(--color-facebook)",
        "shukran": "var(--color-shukran)",
        "shukran-contrast": "var(--color-shukran-contrast)",
        "qitaf": "var(--color-qitaf)",
        "mokafaa": "var(--color-mokafaa)",
        "emkan": "var(--color-emkan)",
        "alfursan": "var(--color-alfursan)",
        "apple": "var(--color-apple)",
        "black-50": "var(--color-black-50)",
        "light-40": "var(--color-light-40)",
        "light-92": "var(--color-light-92)",
        "black-static": "var(--color-black-static)"
      },
      "spacing": {
        "unit": "var(--space-unit)",
        "2xs": "var(--space-2xs)",
        "xs": "var(--space-xs)",
        "sm": "var(--space-sm)",
        "md": "var(--space-md)",
        "DEFAULT": "var(--space)",
        "lg": "var(--space-lg)",
        "xl": "var(--space-xl)",
        "2xl": "var(--space-2xl)",
        "3xl": "var(--space-3xl)",
        "4xl": "var(--space-4xl)",
        "container": "var(--space-container)",
        "card-gap": "var(--space-card-gap)",
        "section": "var(--space-section)"
      },
      "borderRadius": {
        "xs": "var(--rounded-xs)",
        "sm": "var(--rounded-sm)",
        "DEFAULT": "var(--rounded)",
        "lg": "var(--rounded-lg)",
        "popover": "var(--rounded-popover)",
        "full": "var(--rounded-full)"
      },
      "boxShadow": {
        "floating": "var(--elevation-floating)",
        "raised": "var(--elevation-raised)"
      },
      "fontFamily": {
        "display": [
          "var(--type-display-family)"
        ],
        "headline": [
          "var(--type-headline-family)"
        ],
        "title": [
          "var(--type-title-family)"
        ],
        "title-bold": [
          "var(--type-title-bold-family)"
        ],
        "subtitle": [
          "var(--type-subtitle-family)"
        ],
        "subtitle-bold": [
          "var(--type-subtitle-bold-family)"
        ],
        "eyebrow": [
          "var(--type-eyebrow-family)"
        ],
        "body-regular": [
          "var(--type-body-regular-family)"
        ],
        "body-semibold": [
          "var(--type-body-semibold-family)"
        ],
        "body-bold": [
          "var(--type-body-bold-family)"
        ],
        "caption-regular": [
          "var(--type-caption-regular-family)"
        ],
        "caption-semibold": [
          "var(--type-caption-semibold-family)"
        ],
        "meta-regular": [
          "var(--type-meta-regular-family)"
        ],
        "meta-semibold": [
          "var(--type-meta-semibold-family)"
        ]
      },
      "fontWeight": {
        "display": "var(--type-display-weight)",
        "headline": "var(--type-headline-weight)",
        "title": "var(--type-title-weight)",
        "title-bold": "var(--type-title-bold-weight)",
        "subtitle": "var(--type-subtitle-weight)",
        "subtitle-bold": "var(--type-subtitle-bold-weight)",
        "eyebrow": "var(--type-eyebrow-weight)",
        "body-regular": "var(--type-body-regular-weight)",
        "body-semibold": "var(--type-body-semibold-weight)",
        "body-bold": "var(--type-body-bold-weight)",
        "caption-regular": "var(--type-caption-regular-weight)",
        "caption-semibold": "var(--type-caption-semibold-weight)",
        "meta-regular": "var(--type-meta-regular-weight)",
        "meta-semibold": "var(--type-meta-semibold-weight)"
      },
      "fontSize": {
        "display": [
          "var(--type-display-size)",
          {
            "lineHeight": "var(--type-display-lh)",
            "letterSpacing": "var(--type-display-ls)"
          }
        ],
        "headline": [
          "var(--type-headline-size)",
          {
            "lineHeight": "var(--type-headline-lh)",
            "letterSpacing": "var(--type-headline-ls)"
          }
        ],
        "title": [
          "var(--type-title-size)",
          {
            "lineHeight": "var(--type-title-lh)",
            "letterSpacing": "var(--type-title-ls)"
          }
        ],
        "title-bold": [
          "var(--type-title-bold-size)",
          {
            "lineHeight": "var(--type-title-bold-lh)",
            "letterSpacing": "var(--type-title-bold-ls)"
          }
        ],
        "subtitle": [
          "var(--type-subtitle-size)",
          {
            "lineHeight": "var(--type-subtitle-lh)"
          }
        ],
        "subtitle-bold": [
          "var(--type-subtitle-bold-size)",
          {
            "lineHeight": "var(--type-subtitle-bold-lh)"
          }
        ],
        "eyebrow": [
          "var(--type-eyebrow-size)",
          {
            "lineHeight": "var(--type-eyebrow-lh)",
            "letterSpacing": "var(--type-eyebrow-ls)"
          }
        ],
        "body-regular": [
          "var(--type-body-regular-size)",
          {
            "lineHeight": "var(--type-body-regular-lh)"
          }
        ],
        "body-semibold": [
          "var(--type-body-semibold-size)",
          {
            "lineHeight": "var(--type-body-semibold-lh)"
          }
        ],
        "body-bold": [
          "var(--type-body-bold-size)",
          {
            "lineHeight": "var(--type-body-bold-lh)"
          }
        ],
        "caption-regular": [
          "var(--type-caption-regular-size)",
          {
            "lineHeight": "var(--type-caption-regular-lh)"
          }
        ],
        "caption-semibold": [
          "var(--type-caption-semibold-size)",
          {
            "lineHeight": "var(--type-caption-semibold-lh)"
          }
        ],
        "meta-regular": [
          "var(--type-meta-regular-size)",
          {
            "lineHeight": "var(--type-meta-regular-lh)"
          }
        ],
        "meta-semibold": [
          "var(--type-meta-semibold-size)",
          {
            "lineHeight": "var(--type-meta-semibold-lh)"
          }
        ]
      }
    }
  }
};
